### ISSUE TITLE
FATAL: Unable to load template

### ISSUE THREAD

**Issue by tschaub** [jsdoc/jsdoc#1436]
Templates installed from npm fail with an error like this:
```
FATAL: Unable to load template: Cannot find module '/path/to/node_modules/template-name/publish.js/publish'
```

This happens in JSDoc 3.5.4, and I imagine it is due to 415555ed652e32b588870b172b1a3eac2b6ff66f.

To reproduce the issue, install a JSDoc template from npm and run jsdoc.  E.g.
```
npm install jsdoc jsdoc-json
./node_modules/.bin/jsdoc --template jsdoc-json --destination doc.json src
```

This fails because `getResourcePath()` [ends up](https://github.com/jsdoc3/jsdoc/blob/1ff8f555319be223a1b8b2b71928d965fbfafcdd/lib/jsdoc/path.js#L164-L167) calling `require.resolve()` (which is good) and returning the path to the installed template's `main` entry.  Then in the `cli` module, this path is concatenated with `/publish` before being required.

So a `"main": "publish.js"` resolves to `/path/to/node_modules/template-name/publish.js/publish` and we get the `FATAL: Unable to load template...` error (see also #1399).

To work around this issue, instead of using the package name, the path to the template directory can be used (e.g. `jsdoc --template ./node_modules/template-name`).

If there is interest in restoring the old behavior (where the package name could be used for the `--template` value), a second `try` could be added that doesn't concatenate the `main` path with `/publish`.

**Comment by carpiediem** [comment]
The workaround doesn't seem to work on Windows.
```
> node_modules/.bin/jsdoc --template ./node_modules/jsdoc-template src
FATAL: Unable to load template: Cannot find module 'C:\path_to\project\node_modules\jsdoc-template/publish'
```

**Comment by welljsjs** [comment]
> If there is interest in restoring the old behavior (where the package name could be used for the `--template` value), a second `try` could be added that doesn't concatenate the `main` path with `/publish`.

I am currently facing the same issue in 2019. This should at least be mentioned somewhere; it took me some time until I found this issue. 

Is there any update? I'd love to be able to use both. @tschaub (Sorry for waking you up)

**Comment by Laptopmini** [comment]
I'm suffering from the same issue, `JSDoc 3.5.5 (Thu, 14 Sep 2017 02:51:54 GMT)`.

**Comment by danielo515** [comment]
This is a bit dated, but I still face the same problem. I had to instrospect the path of the inkstrap package, determine which path was the one containing the expected file and then add that path to the configuration

**Comment by dirtyredz** [comment]
Ran into this just now as well.
Setting the template in my config file worked for me, thanks.
```template: "./node_modules/template-name"```

**Comment by mayank1513** [comment]
Setting template to `"./node_modules/template-name"`, does not seem to include plugins. Docs are generated, but without use of the plugins specified in the templates field.
