### ISSUE TITLE
Promise typing

### ISSUE THREAD

**Issue by Giuscar** [jsdoc/jsdoc#1482]
I have a function that returns a promise.all(list(ArrayBuffer)).
### Input code
/**
 * @param {string} StringDim
 * @param {string} fileName
 * @return {!Promise.<Array<ArrayBuffer>}
 * @export
 */
function (param){
   [..]
   return Promise.all(list<ArrayBuffer>);
}

### Expected behavior
I expect that my code compiles.

### Current behavior

myScript.js:134: ERROR - inconsistent return type
found   : Promise<Array<?>>
required: (Array<(ArrayBuffer|null)>|null)
    return Promise.all(l);
           ^^^^^^^^^^^^^^

1 error(s), 0 warning(s), 97.7% typed
[ERROR] Build failed

### Your environment

| Software         | Version
| ---------------- | -------
| JSDoc            |  3
|  linux | 16.04

**Comment by hegemonic** [comment]
This does not appear to be an issue with the JSDoc tool.
