### ISSUE TITLE
Cannot add references to other types in @typedef, nor to the type itself.

### ISSUE THREAD

**Issue by robertoost** [jsdoc/jsdoc#1484]
# References and self references
I'm not sure if anyone has ever wanted to do something like this before. When looking at the JSON documentation, it states that a valid JSON object has to be one of certain types. 
```string, number, boolean, null, array, object```

Among those types are arrays and objects, which in turn should be valid JSON themselves. This means that a valid JSON object could contain other valid JSON objects. Defining a simple type to prevent any invalid JSON objects would require the use of two types that contain references to one another.
### The types
```JSONObject```, which contains strings as keys and ```JSONType``` values. 

```JSONType``` which contains strings, numbers, booleans, null values, arrays which have to contain valid JSON values == self reference, and valid JSON objects:  ```JSONObject```.
### The code
```
/**
 * @typedef {{[x: string]: JSONType}} JSONObject - A valid JSON Object.
 */

/**
 * @typedef {(string | number | boolean | null | JSONType[] | JSONObject)} JSONType - A valid JSON type.
 */
```
### The results
Currently, these definitions boil down to

```
type JSONObject = {
    [x: string]: any
}

type JSONType = any
```

Is this the expected behaviour? If so, would references to other types and self references be a nice-to-have functionality?

**Comment by akulara** [comment]
/**
 * @typedef {{[x: string]: JSONType}} JSONObject - A valid JSON Object.
 */

/**
 * @typedef {(string | number | boolean | null | JSONType[] | JSONObject)} JSONType - A valid JSON type.
 */
