### ISSUE TITLE
Documenting since and exceptions for Haruki

### ISSUE THREAD

**Issue by seanoshea** [jsdoc/jsdoc#1504]
I'd like to be able to document since and throws tags for Haruki.

### Input code

```js
/**
 * This is my class which I want to annotate with a since tag.
 * @since 1.0.0
 */
class MyClass {
```

OR

```js
  /**
   * @throws {@link error.APIError} is all goes wrong.
   */
  static aFunctionThatThrows() {
  }
```

### JSDoc configuration
N/A - Haruki does not support these tags at the moment.

### JSDoc debug output
N/A - Haruki does not support these tags at the moment.

### Expected behavior
Haruki should parse these tags and present them in xml format.

### Current behavior
Tags are ignored

### Your environment

| Software         | Version
| ---------------- | -------
| JSDoc            | 3.5.4
| Node.js          | 6.10.2
| npm              | 5.5.1
| Operating system | Mac

**Comment by hegemonic** [comment]
The Haruki template no longer exists on GitHub master, and it won't be included in the next major release. It had many, many problems beyond this one.
