### ISSUE TITLE
Haruki omits documentation for @typedef

### ISSUE THREAD

**Issue by brian-armstrong** [jsdoc/jsdoc#1508]
### Input code

```js
/**
 * Foo is cool.
 * @typedef Foo
 */
```

### JSDoc configuration

`jsdoc foo.js -t templates/haruki -d console -q format=json`

### JSDoc debug output

N/A

### Expected behavior

JSON output should contain description of typedef. In general, the JSON output should capture all comment documentation, so that useful documentation can be generated.

### Current behavior

JSON does not contain description of typedef and possibly other annotations as well.

### Your environment

| Software         | Version
| ---------------- | -------
| JSDoc            | 3.2.2
| Node.js          | 9.5.0
| npm              | 5.6.0
| Operating system | OSX

**Comment by brian-armstrong** [comment]
Fixed by #1507.

**Comment by hegemonic** [comment]
The Haruki template no longer exists on GitHub master, and it won't be included in the next major release. It had many, many problems beyond this one.
