### ISSUE TITLE
[Feature] Export in latex

### ISSUE THREAD

**Issue by YglesEyes** [jsdoc/jsdoc#1522]
Hello,
Export the documentation in html/xml format is very nice but it's not adapted for official documentations.
It could be nice if we can export the documentation in latex format.
What do you think about this idea ?

Regards,

Nicolas PILLON

**Comment by tetedacier** [comment]
Given a jsdoc generated documents set :

```sh
jsdoc -r ./src/* # or any other place where there documented files
```

You can already 'translate' them, using [pandoc](https://pandoc.org/) on jsdoc output dir:
```sh
mkdir -p jsdoc/latex

find ./out -iname "*.html" -type f -exec sh -c 'pandoc "${0}" -o "./jsdoc/latex/$(basename ${0%.html}.latex)"' {} \;

ls jsdoc/latex
```

If you need to 'translate' them into markdown  :
```sh
mkdir -p jsdoc/mardown

find ./out -iname "*.html" -type f -exec sh -c 'pandoc "${0}" -o "./jsdoc/mardown/$(basename ${0%.html}.md)"' {} \;

ls jsdoc/mardown
```

**Comment by hegemonic** [comment]
Another option is to create your own JSDoc template that outputs the docs in LaTeX format. That would be a lot more work than simply using Pandoc or a similar tool, though.

It's unlikely that JSDoc will ever provide built-in LaTeX support, so I'm closing this issue.
