### ISSUE TITLE
Question: Import typedef from another file?

### ISSUE THREAD

**Issue by Legends** [jsdoc/jsdoc#1537]
I need a common place where I can import the typedef from, in order to not define the type `Position` in other used modules over and over again?

Is it possible to have a common file like `common-type-defs.js`,
where I can define `typedef``s for objects which actually don't have a type implementation in form of a class?

For example I have a typedef `Position` which I want to reuse in different modules:
```
/** @typedef {Object} Position
 *  @property {number} column
 *  @property {number} line
 */

/** @typedef {Object} Loc
 *  @property {Position} start
 *  @property {Position} end
 */
```

**common-type-defs.js**
```
/** @typedef {Object} Position
 *  @property {number} column
 *  @property {number} line
 */

/** @typedef {Object} Loc
 *  @property {Position} start
 *  @property {Position} end
 */
```

I need a common place where I can import the typedef from, in order to not define the type `Position` again?
Or do I have to create a `common-types.js` file with an implementation of `Position` and then imort it, like:
/** @typedef {import("./common-types.js").Position} Position*/

or reference typedef
**file1.js**
```
 @reference typedef Position from `common-type-defs.js`  // dummy code

Class XYZ{

   @type {Position} position
   constructor(position){
    ...
   }
}
```

### Your environment

| Software         | Version
| ---------------- | -------
| JSDoc            | ?
| Node.js          | 8.11.3
| npm              | 5.8.0
| Operating system | Win 10

**Comment by mywebstuff** [comment]
Please, make this possible!

**Comment by Frondor** [comment]
This is a great idea, but for a more serious project.
JSDoc has been dying for long time.

**Comment by thw0rted** [comment]
What environment is your code being used in?  You can't always count on having a module loader that understands a static `import` like that.  Presumably your toolchain is resolving it, or maybe discarding it if there are no actual exports from `typedef.js`.

**Comment by mywebstuff** [comment]
I have done that also, but (if I remember correctly) when turning on ts checking with `// @ts-check` you would get errors.
In VSCode the following works for me:

```js
// user.js

const checkAge = require('./user-helper')

/**
 * @typedef {Object} User
 * @property {string} name
 * @property {number} age
 */

/**
 * @param {User} user
 */
const createUser = (user) => {
  if (checkAge(user)) {
    db.save(user)
  }
}
```

```js
// user-helper.js

**Comment by derappelt** [comment]
``

> What environment is your code being used in? You can't always count on having a module loader that understands a static `import` like that. Presumably your toolchain is resolving it, or maybe discarding it if there are no actual exports from `typedef.js`.

Im using it in a webpack toolchain but since the comments are ignored by the js interpreter, it is only for development anyways. 
You are totally right that this is only working in a modular environment but I think if you are working on such a big project that you need your definitions split across multiple files, it's a good idea to use a bundler anyways.
What you can do is wrap the import statement in a "import feature detection" so your editor(which knows how to import) will give you the correct types but a non module environment will just ignore the import

**Comment by derappelt** [comment]
https://gist.github.com/ebidel/3201b36f59f26525eb606663f7b487d0

**Comment by hegemonic** [comment]
For the JSDoc tool, the suggestion from @derappelt is the right way to do this.

**Comment by ayqy** [comment]
@hegemonic As you know, it's not a reasonable approach for **pure types declaration files**, and there are some drawbacks of this approach:

- `import './typedef'` means an exactly real module import, and it's likely to import side effects by accident.

- Importing an empty module file for the typing purpose only may affect build flow, and it's a bit dirty.

What about [TypeScript's import syntax](https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html#import-types), as @mywebstuff mentioned above：

> This syntax is Typescript-specific and differs from the JSDoc standard:

```
// 1.Normal Case
/**
 * @param p { import("./a").Pet }
 */
function walk(p) {
    console.log(`Walking ${p.name}...`);
}

// 2.Alias Type
/**
 * @typedef { import("./a").Pet } Pet
 */

/**
 * @type {Pet}
 */
var myPet;
myPet.name;

// 3.Refer Inferred Type
/**
 * @type {typeof import("./a").x }
 */
var x = require("./a").x;
```

Not perfect, but really ideal for pure declaration files. and it will be a nice feature patch for JSDoc.

**Comment by hegemonic** [comment]
@ayqy That's tracked by #1645.

**Comment by ricardohbin** [comment]
If someone needs a quick patch, I made this branch to fix and jsdoc does not breaks with `import("./a').Foo` syntax (and generate everything ok)

**Comment by ricardohbin** [comment]
If someone needs a quick patch, I made this branch to fix and jsdoc does not breaks with import("./a').Foo syntax (and generate everything ok)

https://github.com/ricardohbin/jsdoc/pull/1

**Comment by thw0rted** [comment]
@hegemonic it looks like #1645 doesn't specifically call out the typescript `import(pathspec)` syntax, from what I can see.  Is that still on the radar?  Is that the right issue to track status for getting it adopted?

**Comment by nbilyk** [comment]
Hi all. 

I wanted this resolved and the jsdoc fork solutions have run stale. I made a small utility that works as a jsdoc plugin, so will hopefully be more forward compatible. 

Give it a try here:
[](https://github.com/polyforest/jsdoc-tsimport-plugin/)

**Comment by briantical** [comment]
For a non-typescript implementation, I found this solution on Stackoverflow. [Here](https://stackoverflow.com/a/55767692/11883716)

**Comment by Dean-NC** [comment]
This works in Visual Studio 2022 (probably older versions too), with a plain .js file: 

typeDefs.js file to define types
```
/**
 * An object describing sorting info
 * @typedef {Object} SortInfo
 * @property {number} queryColNum Column position in the server query
 * @property {boolean} isDescending Whether or not to use descending order
 */

/**
 * A test object
 * @typedef {Object} TestObject
 * @property {string} name Some name
 */
```

.js file to use types
```
/**
 * @typedef {import('./typeDefs.js').SortInfo} SortInfo
 * @typedef {import('./typeDefs.js').TestObject} TestObject
 */

/** @type {SortInfo} */
var mySortInfo
```

**Comment by alystair** [comment]
> Hi all.
> 
> I wanted this resolved and the jsdoc fork solutions have run stale. I made a small utility that works as a jsdoc plugin, so will hopefully be more forward compatible.
> 
> Give it a try here: https://github.com/polyforest/jsdoc-tsimport-plugin/

Shocking that this is still necessary...
