### ISSUE TITLE
How to document `export default function` ?

### ISSUE THREAD

**Issue by msbit** [jsdoc/jsdoc#1539]
Just wanting to see how I can document a module that just exports a function.

An example is:

```
export default function Test (argument) {
  return argument;
};
```

which I would use via:

```
import Test from './Test.js';

Test("HELLO");
```

I've attempted to specify the `@module` and `@param` for the function like so:

```
/** @module Test */

/**
 * @param argument
 */
export default function Test (argument) {
  return argument;
};
```

which does add the module, but the generated page is empty.

Output from the build:

```
$ jsdoc --debug --verbose *
DEBUG: JSDoc 3.5.5 (Thu, 14 Sep 2017 02:51:54 GMT)
DEBUG: Environment info: {"env":{"conf":{"plugins":[],"recurseDepth":10,"source":{"includePattern":".+\\.js(doc|x)?$","excludePattern":"(^|\\/|\\\\)_"},"sourceType":"module","tags":{"allowUnknownTags":true,"dictionaries":["jsdoc","closure"]},"templates":{"monospaceLinks":false,"cleverLinks":false,"default":{"outputSourceFiles":true}}},"opts":{"_":["Test.js","index.js","out"],"debug":true,"verbose":true,"destination":"./out/","encoding":"utf8"}}}
DEBUG: Parsing source files: ["/Users/tom/development/msbit/jsdoc-test/Test.js","/Users/tom/development/msbit/jsdoc-test/index.js"]
Parsing /Users/tom/development/msbit/jsdoc-test/Test.js ...
Parsing /Users/tom/development/msbit/jsdoc-test/index.js ...
DEBUG: Finished parsing source files.
DEBUG: Indexing doclets...
DEBUG: Adding inherited symbols, mixins, and interface implementations...
DEBUG: Adding borrowed doclets...
DEBUG: Post-processing complete.
Generating output files...
Finished running in 0.20 seconds.
```

and screenshot of the output:

![screenshot 2018-06-24 18 36 32](https://user-images.githubusercontent.com/1694533/41817392-8f8ae20a-77dd-11e8-8782-36245d1ca1db.png)

Thanks!

**Comment by BrendonEarl** [comment]
We too are having this issue right now. Has anyone found a solution?

**Comment by jagretz** [comment]
This works, but the doc _needs_ a description. Using the `@param` and `@return` annotations by themselves won't produce any output but the file with the name of the module. eg

```js
/**
 * I am a description...
 *
 * @module
 * @param {number} [num = 0] a number that defaults to zero when not provided.
 * @return {number} the number provided by the caller or the default param.
 */
export default function example(num) {
    return num;
};
```
![jsdoc_example](https://user-images.githubusercontent.com/7716063/45978420-560a5300-c01a-11e8-843c-9dba3eab8854.PNG)

**Comment by pke** [comment]
@jagretz This does not work in current jsdoc 3.6.3

```js
import { useEffect } from "react"

/**
 * Hook to capture key down events.
 *
 * @module
 * @function useKeyDown
 *
 * @example
 * // Calls the `hide` function when the ESC key is pressed down
 * useKeyDown(27, hide)
 *
 * @param {number} keyCode to capture
 * @param {Function} onKey function to call when the key is pressed down
 */
export default function useKeyDown(keyCode, onKey) {

```

**Comment by jrmdel** [comment]
@pke you might want to try the export tag `@exports` since your way of exporting differs from `exports` or `module.exports` [(see here)](https://jsdoc.app/tags-exports.html#syntax)
The documentation also stipulates that for JSDoc 3.3 and later, you need to specify the module name prefixed by `module:` in the export tag
Maybe this could work : 
```javascript
import { useEffect } from "react"

/**
 * Hook to capture key down events.
 *
 * @module myModule
 * @function useKeyDown
 *
 * @example
 * // Calls the `hide` function when the ESC key is pressed down
 * useKeyDown(27, hide)
 *
 * @param {number} keyCode to capture
 * @param {Function} onKey function to call when the key is pressed down
 * @exports module:myModule
 */
export default function useKeyDown(keyCode, onKey) {
```

**Comment by jweird** [comment]
> It doesn't work in version 4 as well. The jsdoc can't generate the correct result if they are together (export and function)

Any update on this as I am getting same issue when you do something like: 

`export default function foo() {
...
}`
