### ISSUE TITLE
Support for JSX Fragments syntax

### ISSUE THREAD

**Issue by bensampaio** [jsdoc/jsdoc#1540]
### Input code

```jsx
import React from 'react';

const MyComponent = (
  <>
    <div>Foo</div>
    <div>Bar</div>
  </>
);
```

### JSDoc configuration

```js
module.exports = {
    opts: {
        destination: './docs/',
        encoding: 'utf8',
        recurse: true,
    },
    recurseDepth: 100,
    source: {
        excludePattern: 'node_modules',
        include: ['src'],
        includePattern: '.+\\.(js|jsx|mjs)$',
    },
    sourceType: 'module',
};
```

### JSDoc debug output

```
ERROR: Unable to parse /project/src/MyComponent.jsx: Unexpected token (4:3)
```

### Expected behavior

File should be parsed with no problems.

### Current behavior

The parsing of the file fails because of JSX Fragment syntax.

### Your environment

| Software         | Version
| ---------------- | -------
| JSDoc            |  3.5.5
| Node.js          | 10.3.0
| npm              |  6.1.0
| Operating system | macOS High Sierra

**Comment by ramsy1980** [comment]
+1

**Comment by bensampaio** [comment]
Is there any update on how to achieve this? I am trying to use `jsdoc-babel` as a plugin with `@babel/preset-react` but that doesn't seem to fix the problem.

**Comment by syntaxval** [comment]
+1

**Comment by axolo** [comment]
+1

**Comment by Wesitos** [comment]
+1

**Comment by james-cordeiro** [comment]
+1

**Comment by dbnapp** [comment]
+1

**Comment by charles4221** [comment]
+1, any news on this?

**Comment by bensampaio** [comment]
The current master branch already supports this but for some reason a new version was not yet released. I tried to get in contact with the author of jsdoc about this but I never got an answer :(

**Comment by hegemonic** [comment]
I've released a new version of JSDoc that should support this.
