### ISSUE TITLE
[Navigation] is it possible to nest modules under namespaces?

### ISSUE THREAD

**Issue by Samuel1989** [jsdoc/jsdoc#1544]
Hi all,

I am a JSDoc noob and have been playing around with it for the past hour and was just wondering if it is possible to generate the documentation so the navigation represents the following:
```
namespace
  - module
      - function
```

What I would like to achieve is to have multiple namespaces with modules beneath them and then functions beneath each module:
```
namespace#1
  - module#1
      - function#1
      - function#2
  - module#2
      - function#1
namespace#2
  - module#1
      - function#1
```

I have tried to use the "memberof" tag to achieve this, but it seems the default generated documentation is very flat, what I actually end up with is:
```
Modules:
  - module#1
  - module#2

Namespaces
  - namespace#1
  - namespace#2
```

Sorry if this is a stupid question, or it has been answered elsewhere (I had looked and hadn't found anything with a straight answer).

Thanks for any help you can provide!

Sam

**Comment by hegemonic** [comment]
I think at least one of the templates listed in JSDoc's `README` does what you're looking for. The default template does not.

If you want to implement this yourself, you could fork the default template; use JSDoc's [`longnamesToTree()` method](https://github.com/jsdoc/jsdoc/blob/be603fd97be231679ce58a08288bd4e07f112f71/lib/jsdoc/name.js#L399) to build a tree of all the longnames that get their own HTML files; and turn that tree into a TOC, [like this code does](https://github.com/hegemonic/jsdoc-baseline/blob/bf3192bace6828dac52c54744cd6e49062c5cb86/lib/publishjob.js#L219). (There are other ways to do this, but that's the one I know.)
