### ISSUE TITLE
Full path to source file is displayed in docs

### ISSUE THREAD

**Issue by racordei** [jsdoc/jsdoc#1557]
Hi Dears,

Full path to source file is displayed in docs when using sources from **multiples** paths.

```
jsdoc C:\scripts\MyScript1.js D:\scripts\MyScript2.js
```

Regards,
Rafael

**Comment by hegemonic** [comment]
That's the intended behavior. If the source files are on the same drive, JSDoc shortens the paths so they're relative to the nearest common ancestor. If the source files are on different drives, there's no common ancestor, so JSDoc uses the paths as-is.
