### ISSUE TITLE
Support debugging and code coverage of jsdoc plugins

### ISSUE THREAD

**Issue by sgilroy** [jsdoc/jsdoc#1564]
I have created a jsdoc plugin for documenting mongoose models, https://github.com/sgilroy/jsdoc-plugin-mongoose but I am finding it challenging to create unit/integration tests because there does not appear to be a way to run jsdoc programmatically in the same process as the test. I believe resolving #938 would be a good way to resolve this, but I am opening this separate issue to ask if there is an alternatives for plugin developers and to share the limited workarounds I have discovered so far.

Have other plugin developers run into this problem, and how have you dealt with it?

I've had some limited success debugging by modifying jsdoc-x to use `--inspect`. Specifically, I added `cmdArgs.unshift('--inspect');` after `cmdArgs.unshift(file);` in `jsdoc-x/src/lib/helper.js`.

I am using jest for testing. To get code coverage, I am using nyc (as suggested in https://github.com/facebook/jest/issues/3190#issuecomment-354758036) and have had some limited success there.

Both of these solutions require extra setup and do not have good IDE integration.

I've also done some unit tests that isolate the plugin and do not use jsdoc itself, but the primary difficulty with this is instead of providing JavaScript code with JSDoc comments for the test, I have to manually create mock AST objects. I'm interested in directly using babylon as a parser to get appropriate AST nodes and pass these to the plugin, but I haven't tried this yet. 

### Input code

Below is an example of a jsdoc plugin test using jsdoc-x.
```js
const jsdocx = require('jsdoc-x');

function parseJsdoc(source) {
  return jsdocx.parse({
    plugins: ['index'],
    undocumented: false,
    source
  });
}

it('should do nothing for code with no mongoose schema', () => {
  return expect(parseJsdoc('const simple = true;')).resolves.toEqual([]);
});

describe('with mongoose.Schema', function() {
  it('should add class documentation', async () => {
    const results = await parseJsdoc(`const mongoose = require('mongoose');

/**
 * Blog post
 */
const BlogSchema = new mongoose.Schema({});`);

    expect(results[0]).toHaveProperty(
      'comment',
      `Blog post
@class Blog
@extends mongoose.Model`
    );
  });

  it('should add member documentation to schema path', async () => {
    const results = await parseJsdoc(`const mongoose = require('mongoose');

const BlogSchema = new mongoose.Schema({
  /**
   * Title of the blog post which will be used as the header.
   */
  title:  String
});`);

    expect(results[1]).toHaveProperty(
      'comment',
      `Title of the blog post which will be used as the header.
@memberof Blog#
@member {String} title`
    );
  });
});
```

### Your environment

| Software         | Version
| ---------------- | -------
| JSDoc            | 3.5.5
| Node.js          | 10.3.0
| npm              | 6.1.0
| Operating system | macOS 10.11.6

**Comment by sgilroy** [comment]
I came up with another workaround using the parser from jsdoc. My initial attempt to just require `jsdoc/lib/jsdoc/src/parser` was not successful, but with some initialization and mocking I was able to get this working. See below or https://github.com/sgilroy/jsdoc-plugin-mongoose/blob/master/__tests__/unit/plugin-with-parser.js#L1-L104

This solution is rather complicated and fragile. Any suggestions for simplifying or improving would be appreciated, and of course changes to jsdoc to allow for simpler unit tests of plugins would be great.

```js
const _ = require('lodash');
const plugin = require('../../index');

/*
jsdoc does not provide an API to use it programmatically. As a workaround, these tests initialize jsdoc and then
with the help of some mocking by jest, use the internal jsdoc parser to build and walk the AST to simulate what
jsdoc does and allow the plugin to be tested.
*/

// Note that in order for these jest.mock and require statements to succeed, we need NODE_PATH=./node_modules/jsdoc/lib
jest.mock('jsdoc/env');
const envMock = require('jsdoc/env');

// require in order to initialize jsdoc
require('jsdoc/jsdoc');

// override the mocked env.conf with the conf initialized in the global env from the above require
/*eslint no-undef: "off"*/
envMock.conf = env.conf;

const jsdocParser = require('jsdoc/lib/jsdoc/src/parser');

const parser = jsdocParser.createParser();
const sourceName = 'fake.js';

/**
 * Exercise the visitNode method of the plugin by treating the program function as if it were a file with JSDoc
 * commented code and then passing the specified node to the plugin's visitNode method.
 *
 * @param {Function} program Function with a body of JSDoc commented code to test
 * @param {String} nodePath Relative path to the AST node that should be visited, specified from the body of the program function
 * @return {Object} Event object that results from the plugin visiting the node
 */
function visitNode(program, nodePath) {
  const source = program.toString();
  const ast = parser._astBuilder.build(source, sourceName);
  let event = {};

  // find any existing jsdoc comment
  parser.on('jsdocCommentFound', _event => {
    event = _event;
  });

  // walk the AST to set the parent of each node
  parser._walkAst(ast, parser._visitor, sourceName);
  const node = _.get(ast, 'program.body[0].expression.body.' + nodePath);

  plugin.astNodeVisitor.visitNode(node, event);

  return event;
}

it('should do nothing for code with no mongoose schema', () => {
  const event = visitNode(() => {
    Math.abs(1);
  }, 'body[0]');
  expect(event).not.toHaveProperty('comment');
});

describe('with mongoose.Schema', function() {
  it('should add class documentation', async () => {
    const event = visitNode(() => {
      const mongoose = require('mongoose');

      /**
       * Blog post
       */
      const BlogSchema = new mongoose.Schema({});
      mongoose.model('Blog', BlogSchema);
    }, 'body[1].declarations[0]');

    expect(event).toHaveProperty(
      'comment',
      `Blog post
@class Blog
@extends mongoose.Model`
    );
  });

  it('should add member documentation to schema path', async () => {
    const event = visitNode(() => {
      const mongoose = require('mongoose');

      const BlogSchema = new mongoose.Schema({
        /**
         * Title of the blog post which will be used as the header.
         */
        title: String
      });
      mongoose.model('Blog', BlogSchema);
    }, 'body[1].declarations[0].init.arguments[0].properties[0]');

    expect(event).toHaveProperty(
      'comment',
      `Title of the blog post which will be used as the header.
@memberof Blog#
@member {String} title`
    );
  });
});
```

**Comment by JustinBeaudry** [comment]
I had a similar issue and opted to use `spawn` from `child_process` to call the jsdoc cli via `npx jsdoc` and passed in the `--explain` (or `-X`) param to have JSON returned, and then parsed that.

```javascript
const {spawn} = require('child_process');
const jsdoc = () => {
  return new Promise((resolve, reject) => {
    // using locally installed jsdoc
    const jsdoc = spawn('npx', [
      'jsdoc',
      // pass jsdoc cli options here
      '-c',
      'conf.json',
      '-X'
    ]);
    let output = '';
    let err = '';
    jsdoc.stdout.on('data', data => { output += data });
    jsdoc.stderr.on('data', data => { err += data });
    jsdoc.on('close', code => { code > 0 ? reject(err) : resolve(output) });
  });
};
```

**Comment by hegemonic** [comment]
I know this is a problem. Unfortunately, I think providing programmatic access to JSDoc is the right way to solve it. (I say "unfortunately" because that's not a quick and easy fix.)

Here's a ~~disgusting hack~~ trick that I've used to test a JSDoc template: [Patch `require()` the same way that JSDoc does](https://github.com/hegemonic/jsdoc-baseline/blob/bf3192bace6828dac52c54744cd6e49062c5cb86/gulpfile.js#L24), then [set up a minimal environment](https://github.com/hegemonic/jsdoc-baseline/blob/bf3192bace6828dac52c54744cd6e49062c5cb86/test/helpers/index.js#L27). Still fragile, admittedly.
