### ISSUE TITLE
How to remove the (inner) in the generated doc

### ISSUE THREAD

**Issue by majaray** [jsdoc/jsdoc#1565]
I have a following code that I want to generate a doc for it.

```js
/**
 * @module utils
 */

/**
 * Shuffle an array with "Fisher–Yates shuffle algorithm"
 * @param {array} array An array that you want to shuffle
 * @returns {array} The array after shuffle
 **/
function shuffleArray(array) {
    let counter = array.length;

    // While there are elements in the array
    while (counter > 0) {
        // Pick a random index
        let index = Math.floor(Math.random() * counter);

        // Decrease counter by 1
        counter--;

        // And swap the last element with it
        let temp = array[counter];
        array[counter] = array[index];
        array[index] = temp;
    }

    return array;
}

export default {
    shuffleArray,
}

```

### JSDoc configuration
no custom configuration

### Expected behavior
All the functions are grouped by module, without (inner) tag.

### Current behavior
All functions are grouped by module, all prefixed with a (inner) tag

### Your environment

| Software         | Version
| ---------------- | -------
| JSDoc            | 3.5.5
| Node.js          | 8.11.1
| npm              | 5.6
| Operating system | macOS

I want to remove the (inner) tag in all the generated docs.
I tried `@public`, `@protected` in the comment but none of them working. I guess it might because of the structure of my code.
Any help would be appreciated!

**Comment by lll000111** [comment]
Declare the function `@static` if it is static and it will now say "static" instead of "inner", which in your example code would be correct.

**Comment by greggman** [comment]
I'm running into this issue as well. Something changed between the versions of JSDoc. I used to only get docs for functions I marked with

     /*  @memberOf module:myModule

But after updating to the latest vs grunt-jsdoc (1.1 -> 2.2) all what used to be private functions are showing up in the docs tagged in "inner".

How can get those functions not to appear in the docs?

**Comment by jakeknerr** [comment]
Try ```@ignore``` on the function you don't want in the docs.

**Comment by lll000111** [comment]
Or `@private` :-)

**Comment by greggman** [comment]
Thanks. now to go update a few hundred functions and typedefs 😭

**Comment by Fr0sT-Brutal** [comment]
Is export detection working?
```
/**
  @module foo
 */

/** foo */
let foo;

module.exports =
{
	foo
}
```
Outputs "foo" as "inner".

**Comment by hegemonic** [comment]
I think this got sorted out, kind of.

@Fr0sT-Brutal No, that doesn't work right now. See #1645.
