### ISSUE TITLE
Feature Request: alternateClassName(s)

### ISSUE THREAD

**Issue by tobiu** [jsdoc/jsdoc#1569]
Same as:
https://github.com/senchalabs/jsduck/wiki/@alternateClassName

In case you want to map classes to a namespace and create "shortcuts" for the ones which get used a lot. E.g.

Neo.component.Component
Neo.Component

It would be very useful to show them in the docs multiple times as well (best including the real and alternate names on top level)

best regards
tobias

**Comment by JustinBeaudry** [comment]
@tobiu Couldn't you just use [@alias](http://usejsdoc.org/tags-alias.html)?

**Comment by tobiu** [comment]
Hi @JustinBeaudry,

this is a pretty old thread. I am crafting a ES8 based UI framework which runs inside web workers and at the time I created this feature request, it was not possible for me to use @ class (had to stick to @ module instead).

I ended up using jsdoc-x to create a custom json based output, ignoring everything but comments (there were too many issues).

At this point, I also crafted a custom docs app using the new framework.
Added 2 example screenshots.

![Screenshot 2019-03-13 at 18 02 58](https://user-images.githubusercontent.com/1177434/54299176-9f476280-45ba-11e9-895c-d0531b3a7737.png)

![Screenshot 2019-03-13 at 18 08 19](https://user-images.githubusercontent.com/1177434/54299448-34e2f200-45bb-11e9-95b4-c93f60243f6f.png)

I think I could use @ alias now, since I am manually parsing the output anyway.

In case you are interested, I can add you to the repo.

Best regards
Tobias

**Comment by JustinBeaudry** [comment]
@tobiu Yeah, I figured as much, but was going through old issues that haven't been commented on, and thought I'd reply regardless. 

> In case you are interested, I can add you to the repo.

looks interesting! I'd love to take a look!
