### ISSUE TITLE
It seems hard to implement tag similar like 'module' is impossible by using just plugin system

### ISSUE THREAD

**Issue by maple-leaf** [jsdoc/jsdoc#1576]
I wanna create two tags, component and directive, which behavior is same with `module` tag.
So far, I can find a way to achieve this by just using plugin.
Please check this fork changes: https://github.com/jsdoc3/jsdoc/compare/master...maple-leaf:master
And readme: https://github.com/maple-leaf/jsdoc#whats-changed

If this can be done by using plugin, I'll happy to create one instead of changing jsdoc source code. :-)

**Comment by hegemonic** [comment]
JSDoc has lots of other code that gives modules special treatment, so you're right, you can't get the same behavior as modules just by writing a plugin. Sorry about that.
