### ISSUE TITLE
How to output documentation files directly to output directory?

### ISSUE THREAD

**Issue by balupton** [jsdoc/jsdoc#1588]
If I'm running:

```
jsdoc --recurse --pedantic --access all --destination ./docs --package ./package.json --readme ./README.md --template ./node_modules/minami ./source
```

I will get an output `docs` directory like so:

<img width="263" alt="screen shot 2018-11-14 at 1 05 08 pm" src="https://user-images.githubusercontent.com/61148/48455100-02440b00-e80e-11e8-9199-6c3327f88156.png">

Is there any configuration so that the package name and package version directories are not created, so that the docs html files etc are put directory into the specified docs directory? Such that I get this instead:

<img width="223" alt="screen shot 2018-11-14 at 1 07 15 pm" src="https://user-images.githubusercontent.com/61148/48455170-3e776b80-e80e-11e8-83a4-5e67679ff088.png">

As [our existing documentation.js setup](https://github.com/bevry/awesome-travis/blob/a16fffacc146944edb58d02bbc565bf467099b18/scripts/surge.bash#L61-L81) already deploys each documentation to URLs specific to their commits, branches, and tags (versions), so there is no need for such jsdoc behaviour here.

As a workaround, I've updated my npm script to be:

```
rm -Rf ./docs && jsdoc --recurse --pedantic --access all --destination ./docs --package ./package.json --readme ./README.md --template ./node_modules/minami ./source && mv ./docs/$npm_package_name/$npm_package_version/* ./docs/ && rm -Rf ./docs/$npm_package_name/$npm_package_version
```

**Comment by JustinBeaudry** [comment]
This depends on your templates `publish.js` function. The default template uses `pkg.name/pkg.version`as output directory prefixes, and [doesn't appear to support any means of overriding this behavior](https://github.com/jsdoc3/jsdoc/blob/3.5.5/templates/default/publish.js#L503). :-(

**Comment by Laptopmini** [comment]
- Fork the template
- In `publish.js`, comment out the lines:
```
packageInfo = ( find({kind: 'package'}) || [] )[0];
if (packageInfo && packageInfo.name) {
    outdir = path.join( outdir, packageInfo.name, (packageInfo.version || '') );
}
```
- Add your forked template as a dev dependency and reference it from your `.jsdoc.json` config file:
```
"opts": {
  "template": "./node_modules/your-forked-template"
}
```

Thanks @JustinBeaudry for the tip

**Comment by hegemonic** [comment]
Another option is to run JSDoc with the flag `--package ''`, which essentially tells JSDoc to ignore the `package.json` file.

**Comment by walkermatt** [comment]
The [clenemt/docdash template](https://github.com/clenemt/docdash/) recently added options that allow excluding the package scope, name and version from the path. They haven't made it to a release yet but [can be installed from the repo as per this comment](https://github.com/clenemt/docdash/issues/89#issuecomment-775969849).
