### ISSUE TITLE
documenting factory and returns

### ISSUE THREAD

**Issue by prasannavl** [jsdoc/jsdoc#1589]
### Input code

```js
/** Description of the function
 *  @name StoreFactory
 *  @function
 *  @returns {??}
*/

/**
 * Retrieve a specific application store
 * @param {StoreFactory} factory 
 * @returns {??}
 */
function getOrCreateStore(name, factory) 
```

There are clear constraints here. How would one document these returns? To be specific I'm also hoping TypeScript's salsa can take advantage of it and provide Intellisense based on this, if there was a way to do this correctly.  

This function is guaranteed to return a *single type per factory* - but it's generic on the accompanying factory function (the factory is going to be of a type (x) => T, where returns of this function is T, which is also the return of the factory).

**Comment by JustinBeaudry** [comment]
```javascript
/** Description of the function
 *  @name StoreFactory
 *  @function
 *  @returns {function(string, number): Store}
*/
```
You can see a full example above of documenting the `function` type. Here's the breakdown:

- `{function}` - declare a function type without declaring it's parameters or return type
- `{function(string, number)}` - declare a function type and declare it's parameter types
  - `{function((object.<string, string>|string[]))` - tip:  you can use type unions, rest parameters, etc. in a function parameters and return type definition. SEE:  http://usejsdoc.org/tags-type.html
- `{function(string, number): (object.<string, string>|string[])` - declare a function type while declaring it's parameters and return type.

**Comment by prasannavl** [comment]
@JustinBeaudry, thanks for the breakdown. 

However, just reading through my post, I just realised I hadn't communicated it clearly. Sorry about that. Just updated it. Basically, 

```
The function is guaranteed to return a single type per factory - but it's generic on the accompanying factory function (the factory is going to be of a type (x) => T, where returns of this function is T, which is also the return of the factory).
```

This is what the tricky part was. I'm not entirely sure if this relationship is really representable today with jsdoc.

**Comment by hegemonic** [comment]
I suggest using the [`@typedef` tag](https://jsdoc.app/tags-typedef.html) to define the type that `StoreFactory` returns, then replace `??` in your examples with the name of the typedef.

I have no idea whether TypeScript will understand that syntax, though. Sorry.
