### ISSUE TITLE
Cannot set breakpoint correctly in publish function in custom template

### ISSUE THREAD

**Issue by shrinktofit** [jsdoc/jsdoc#1591]
The breakpoint always paused to next line...

I use vscode as debugger.

**Comment by lll000111** [comment]
Do I understand that right, you have a problem with debugging with VSCode? It just happens to be when debugging JSDoc code? That would still be a VSCode issue.

**Comment by hegemonic** [comment]
It's unclear whether this issue has anything to do with JSDoc, so I'm closing it.
