### ISSUE TITLE
Is it possible to format module name

### ISSUE THREAD

**Issue by marko-mlinarevic** [jsdoc/jsdoc#1594]
Is is possible to format module name for example

```
@module <strong>ModuleName</strong>

```

Thank you for the answer

**Comment by lll000111** [comment]
Yes, you have to edit the *template*. Go to the sources, copy one of the templates,

https://github.com/jsdoc3/jsdoc/tree/master/templates

edit the template, edit your configuration file to tell jsdoc3 CLI tool to use that template.
