### ISSUE TITLE
deprecate modifier

### ISSUE THREAD

**Issue by deadmann** [jsdoc/jsdoc#1600]
when you are deprecating something the intellisense will deprecate it in all places....
although the parameter may be really required by the class/file/some scope of codes

it will be nice to add some modifier, so we can tell the intellisense that this class can access these variable, but they are deprecated if a user want to access them from outside of noted scope, and that it can cause issues if accessed directly. and using deprecation message, we redirect user to the usable parameter

**Comment by hegemonic** [comment]
This sounds like an issue with your IDE, not with the JSDoc tool.
