### ISSUE TITLE
Does not detect private properties in ES6 modules

### ISSUE THREAD

**Issue by rugk** [jsdoc/jsdoc#1605]
### Input code

```js
/**
 * Shows random tips to the user.
 *
 * @module RandomTips
 */

/**
 * @private
 * @type {Object}
 */
const PRIVATE_EXPLICIT_OBJECT = {}

/**
 * @type {Object}
 */
const PRIVATE_IMPLICIT_OBJECT = {}

/**
 * @type {Object}
 */
export const PUBLIC_THING = {}
```

### JSDoc configuration

```js
{
    "plugins": [
        "plugins/markdown"
    ],
    "opts": {
    	"readme": "README.md",
        "template": "~/.npm-packages/lib/node_modules/docdash",
        "encoding": "utf8",
        "destination": "docs/",
        "recurse": true,
        "verbose": true
    },
    "templates": {
        "cleverLinks": true,
        "monospaceLinks": false
    },
    // …
}
```

### JSDoc debug output
nothing special, I can assure you

### Expected behavior

`PRIVATE_IMPLICIT_OBJECT` should not appear in the output, as JSDOC should automatically detect that it is not exported and used only in this module. As such, it should not force me to require to mark it is `@private` as I did in `PRIVATE_EXPLICIT_OBJECT`.

Note that it does not appear in the doc, if I do not document it at all via jsdoc comments. Thus, this discourages documenting some internal (private) variables, which is not good, IMHO.

### Current behavior

`PRIVATE_IMPLICIT_OBJECT` actually appears in the JSDOC document while `PRIVATE_EXPLICIT_OBJECT` does not. IMHO, this is very strange, as in ES6 modules all variables are automatically private, unless you [`export`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export) them. As such `PUBLIC_THING` is e.g. okay to be expected public (or protected), but otherwise it makes no sense…

### Your environment

| Software         | Version
| ---------------- | -------
| JSDoc            | 3.5.5
| Node.js          | v10.15.0
| npm              | 6.4.1
| Operating system | Fedora 29

**Comment by rugk** [comment]
Even worse, even if I use JSDOC just to document variables inside of a function, they get added to the JSDOC:

```js
/**
 * It's a private(!) function…
 *
 * @private
 * @param  {string} dataSetValue
 * @returns {string}
 */
function convertDatasetToAttribute(dataSetValue) {
    // with a small JSDOC, but this variable below is anyway added to the JSDOC output
    /** {@link https://regex101.com/r/GaVoVi/1} **/
    dataSetValue = dataSetValue.replace(/^[A-Z]/, (char) => char.toLowerCase());
}
``` 

I should have said, it mentions these are "_inner_ variables", but only if I explicitly set them to private, they are actually excluded.

**Comment by rugk** [comment]
Oh, wait, I found my error. It seriously requires `@public` or so in the module description too. Then it behaves as expected.

However, I still think this behavior is strange and also not really documented anywhere.

**Comment by lll000111** [comment]
I think you misinterpret what "private" means. 

Have a look at these examples: http://usejsdoc.org/tags-access.html

This tag is purely "for your information" and virtual, it has no connection to the JS code. What I mean is, this isn't a documentation of what a JS runtime actually does, like scope and visibility, this is about *what you want*.

The context are JS pseudo-classes, where real privacy is not possible (using functions and lexical scopes it's of course no problem to make something really private in this language). All the examples are for pseudo-class style, documenting variables or even any other than that pseudo-class based coding style seems to be an afterthought. It's still possible, but to see what some tag is supposed to mean and how it works always is based on that one style.

So what happens is this:

If you declare

```
/**
 * @private
 * @module
 */
```

then everything in that module will be private, and not appear in the output (can be overridden in the configuration).

Without `@private` everything that is not explicitly marked as private will appear in the output for that module. You have to set individual symbols (const, function, etc.) to `@private` explicitly.

It's actually not too bad once you understand it.

**Comment by rugk** [comment]
> The context are JS pseudo-classes, where real privacy is not possible (using functions and lexical scopes it's of course no problem to make something really private in this language).

I guess that is the problem. Because actually, in ES6 modules **real privacy is possible**. So e.g. when a variable is not exported (as `PRIVATE_IMPLICIT_OBJECT`), you really **cannot use it from the outside** (unless you embed it into an object that you then actually export or so, but then the object is public, not really the var inside the object).

> The question is why document something with JSDoc that is not meant to be part of the API anyway?

There are several arguments here, e.g.:
* I want to document the source code for contributors, too, not only for API users.
* Generally, the question "why do you document your code?" is a bit off, as that is obviously best practise for reasons. And yes, I could not use the JSDoc syntax, but if you have a hammer to drive in the nail, why use your pure hands? (e.g. editors often support syntax highlighting for JSDoc)
* Editors as Visual Studio Code support "hovering" on variables that display it's comment/type then. This works for private vars, too, of course, but only if actually documented, obviously...
* Or as in [my second comment](https://github.com/jsdoc3/jsdoc/issues/1605#issuecomment-455893236) I just wanted to add a proper link

> If the parent is private something inside of it should not be not private. After all, it works that way on the @module level.

Yes the whole example was, so it was module level (ES6), too:
````js
/**
 * Some module
 *
 * @module foo
 */

/**
 * It's a private(!) function…
 *
 * @private
 * @param  {string} dataSetValue
 * @returns {string}
 */
function convertDatasetToAttribute(dataSetValue) {
    // with a small JSDOC, but this variable below is anyway added to the JSDOC output
    /** {@link https://regex101.com/r/GaVoVi/1} **/
    dataSetValue = dataSetValue.replace(/^[A-Z]/, (char) => char.toLowerCase());
}
```

And even though it is actually inside of a private function, it is inside of a (as I know now) publicly assumed module. Maybe that is causing this behaviour.
Still think this is strange/unintuitive, because when you initialize a variable inside of a function in JS, it also does have this scope and cannot be used outside of that function.

**Comment by rugk** [comment]
I guess the problem behind this all is, that before ES6 modules were used, the semantic of stuff like private/public was different than it is now. And JSDoc was built for this ("old") JS. But JS is evolving, and now we have proper privates that can be easily parsed/interferred from the source code itself.

**Comment by hegemonic** [comment]
As you noticed, when JSDoc finds a documented variable in a module, and the variable isn't exported from the module, JSDoc's output shows the variable as an _inner variable_. That's how things have worked for a very long time.

The situation you're describing is not unique to ES2015 modules—you'd see the same behavior with CommonJS modules.

To suppress these variables from the output, just don't document them, or include the `@private` tag in the docs.
