### ISSUE TITLE
documenting Function assigned to module.exports

### ISSUE THREAD

**Issue by esatterwhite** [jsdoc/jsdoc#1614]
Documenting a function as a module is showing up in the globals section in addition to it being documented as a module

### Input code
```javascript
/**
 * @module color/mixer
 **/

/**
 * Blend two colors together.
 * @param {string} color1 - The first color, in hexadecimal format.
 * @param {string} color2 - The second color, in hexadecimal format.
 * @return {string} The blended color.
 **/
module.exports = function(color1, color2) {
    // ...
};
```
### Expected behavior

The function should be documented as a module only.

### Current behavior

it is being documented in the list of modules, but also being documented as a global

### Your environment

| Software         | Version
| ---------------- | -------
| JSDoc            | 3.5.5
| Node.js          | 10
| npm              | 6.4.1
| Operating system | linux

**Comment by JustinBeaudry** [comment]
I'm not sure, but this might require the [`@function` tag](http://usejsdoc.org/tags-function.html).

**Comment by hershmire** [comment]
Is this a bug or can this be solved in a specific way?

**Comment by hegemonic** [comment]
I can't reproduce this issue in JSDoc 3.6.1. Using your input code, the default template does not show any globals in the TOC.

Please try this again with JSDoc 3.6.1, and please test with the default template if you haven't already (because this could also be a template issue).
