### ISSUE TITLE
How to use decorators with JSDoc 3 and Babel.js?

### ISSUE THREAD

**Issue by HamedFathi** [jsdoc/jsdoc#1615]
I want to comment on a field with decorator like

```js
class Point {
  constructor(x, y) {
    // ...
  }

  /**
   * a variable with decorator
   */
  @test() val;

  getX() {
    // ...
  }

  getY() {
    // ...
  }

  static fromString(str) {
    // ...
  }
}
```

but I got an error

`Stage 2 decorators may only be used with a class or a class method (10:2)`

How to fix it? Is it possible to comment on decorators? How to config JSDoc Babel parser for this use case?

**Comment by JustinBeaudry** [comment]
This issue is more likely an issue with your `.babelrc` then an issue with jsdoc. 

See the babel plugin here: https://babeljs.io/docs/en/babel-plugin-proposal-decorators, and some information on decorators here: https://github.com/wycats/javascript-decorators/blob/master/README.md.

**Comment by HamedFathi** [comment]
@JustinBeaudry 
I know about Babel.js and this feature but Can I override JSDoc `.babelrc` with my own options? I think they should add all plugin proposal to `.babelrc` not me.

**Comment by JustinBeaudry** [comment]
I don't think JSDoc3 supports stage 2 spec features; code that is not ES2015. You would probably have to transpile first, then run JSDoc on your transpiled code.

**Comment by JustinBeaudry** [comment]
It uses the @babel/parser and doesn't look like it's searching for a projects `.baberc`. So to answer your question it doesn't appear that it's currently possible to use your projects `.babelrc`. Unless you hack it together yourself, which is probably not worth it. Seems this is a legitimate issue.

**Comment by hegemonic** [comment]
I believe that @JustinBeaudry is correct. JSDoc uses Babel's JS parser; if the latest version of Babel doesn't support your code, chances are high that JSDoc won't support it either.
