### ISSUE TITLE
Move triple lined comment support to be 1st class?

### ISSUE THREAD

**Issue by orta** [jsdoc/jsdoc#1624]
Hi there 👋 

I know about https://github.com/jsdoc3/jsdoc/issues/1237 which was mainly about the existence of supporting `/// docs` - I'd like to go a step further and make a request that `///` be considered a first class citizen in JSDoc. 

This desire comes mainly because I'd like my dev-tools like VS Code to support this, and to make it less effort to do single line comments which should be attached to expressions for docs. Code which I think would benefit from switching to `///` tends to be [long sections of code with lots of small contextual comments](https://github.com/danger/danger-js/blob/dfe45354346311c35da9ceb55e01786a8b2a3615/source/dsl/GitHubDSL.ts#L164-L460) (TypeScript here is documenting the params etc, here's [the Swift equivalent](https://github.com/danger/swift/blob/db863cd329d49e762192655ecafe7de22ab1176e/Sources/Danger/GitHubDSL.swift#L75-L145))

Happy to explore the grunt work for this, if someone offers a bit of advice what it'd take to make it work 👍

**Comment by hegemonic** [comment]
I don't think the demand for this feature is large enough to justify making the change. Also, VS Code doesn't actually use any code from JSDoc, so there's no guarantee that a JSDoc change would result in a VS Code change.

I'd be happy to reconsider if more demand emerges, but for now, please use the `commentConvert` plugin.

**Comment by orta** [comment]
Connecting this issue to the TypeScript PR which would bring support for `///` inside vscode: https://github.com/microsoft/TypeScript/pull/39930
