### ISSUE TITLE
Use jsdoc types from node_module without requiring file

### ISSUE THREAD

**Issue by cyrilchapon** [jsdoc/jsdoc#1627]
Hey.

I'm writing a tool that is able to run database migrations, just like [sequelize-cli](https://github.com/sequelize/cli). This tool dynamically `require`s some migration files, that end up being like this :

```
module.exports = {
  up: () => {},
  down: () => {}
}
```

The migration script requires it, and then execute the according method. The `up` and `down` methods are then passed some arguments, like a Sequelize `QueryInterface` for example.

I'd like to statically annotate those arguments, to get some benefits like Visual Studio Code autocompletion inside migration files.

... but as for now, the trouble is "requiring the file holding the type definition"...

The only way I found to make this working is like this :

```
/* eslint-disable no-unused-vars */
const SequelizeQueryInterface = require('sequelize/lib/query-interface')
const Sequelize = require('sequelize')
/* eslint-enable no-unused-vars */

module.exports = {
  /**
   * @param {SequelizeQueryInterface} sqlQueryInterface
   * @param {Sequelize} Sequelize
   */
  up: (sqlQueryInterface, Sequelize) => {
    // <-- Types hint in VS Code work here
  },

  /**
   * @param {SequelizeQueryInterface} sqlQueryInterface
   * @param {Sequelize} Sequelize
   */
  down: ({ sqlQueryInterface, Sequelize }, { mongoConnection, Mongoose }) => {
    // <-- Types hint in VS Code work here
  }
}
```

As you can see, I'm forced to actually require the source file in order to "import" and then use its type definition.

The question is simple :
**Is there a better way (not involving `require`) to tell JSDoc where to find the types ?**

**Comment by hegemonic** [comment]
This sounds like a VS Code issue, not a JSDoc issue. (VS Code does not use the actual JSDoc tool to parse JSDoc-style tags.)

**Comment by cyrilchapon** [comment]
The question is broader than just VS code actualy.

It's more like "how to use jsdoc types for function arguments where type inference is defeated, without having to actualy require the source file"

**Comment by Rfrixy** [comment]
@cyrilchapon  use the import functionality within jsdoc to get around this. This will work without the requires -
```
  /**
   * @param { import('sequelize/lib/query-interface')} sqlQueryInterface
   * @param { import('sequelize') } Sequelize
   */
```

**Comment by hhoangg** [comment]
Sorry for reopening the topic
I had the same problem, and more precisely it didn't work when I installed the `sequelize-cli` package into `devDependencies`
after moving `sequelize-cli` to `dependencies` instead of `devDependencies` it worked.
May I ask is there a way to make it work even if it is installed in `devDependencies`?
