### ISSUE TITLE
Security Warning due to usage of library marked <0.6.2

### ISSUE THREAD

**Issue by laberning** [jsdoc/jsdoc#1634]
This is actually a follow up of issue https://github.com/jsdoc3/jsdoc/issues/1200.
When using jsdoc 3.5.5 it still seems to rely on marked ~0.3.6 which has been reported to contain a vulnerability of "regular expression denial of service".

```
                       === npm audit security report ===


                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance

  Moderate        Regular Expression Denial of Service

  Package         marked

  Patched in      >=0.6.2

  Dependency of   jsdoc [dev]
```

**Comment by krampstudio** [comment]
Should be fixed by https://github.com/jsdoc3/jsdoc/pull/1633

**Comment by r-springer** [comment]
Even the current state on `master` would work as it installs the most recent patch version of marked `0.6.x`. But we will need a new release, since the most recent version is 3.5.5 which uses `~0.3.6` (as pointed out by @laberning).

**Comment by eaviles** [comment]
Any idea on when this will be released? Thanks in advance!

**Comment by lll000111** [comment]
@eaviles There is a reply from *hegemonic* here: https://github.com/jsdoc3/jsdoc/issues/1530#issuecomment-488551061 I don't agree with his last paragraph there, by the way. This isn't personal and this is not a personal hobby project for its many users. This is orthogonal to who does what with their private time, there is no strict binding to exactly one person except by the owner's choice.

**Comment by hegemonic** [comment]
I'm releasing JSDoc 3.6.0 shortly, which will use a current version of `marked`.
