### ISSUE TITLE
Define type as return value of a function

### ISSUE THREAD

**Issue by xileftenurb** [jsdoc/jsdoc#1638]
I want to define a type as being the return value of a function.

the intellisense is able to accuratly determine the return value of a function, but I cannot the returns value in other jsdoc definition.

by exemple, I would like to be able to do :

```js
/**
    the returns value is implicit as it is complexe and I don't want 
     to rewrite it in jsdoc.
*/
function createSomething() {
   //do thing
   //return something
}

const something = createSomething()

/**
    I would like to say that 'something' must be the same as 
    what is returned by "createSomething"
*/
function needSomething(something) {
     //the type of 'something' is lost.
}
```

I think this is similar to issue #1244 and #1086.

I also need to be able to get the return value of the return value of a function, for curried function. 

thank a lot

**Comment by lll000111** [comment]
> the returns value is implicit as it is complexe and I don't want to rewrite it in jsdoc.

Why do you ask here, then? This tool's whole purpose is to create offline (e.g. HTML) documentation from your inline JSDoc comments.

> I would like to say that 'something' must be the same as what is returned by "createSomething"

Create a type then. It can be a dummy type, just a name, and document `createSomething`'s return value as well as `needSomething`'s parameter.

**Comment by hegemonic** [comment]
I agree that this issue is not related to the JSDoc tool.
