### ISSUE TITLE
Redirect usejsdoc.org to jsdoc.app

### ISSUE THREAD

**Issue by ungoldman** [jsdoc/jsdoc#1642]
Not sure if this is the right place to report, but http://usejsdoc.org appears to be down.

https://downforeveryoneorjustme.com/usejsdoc.org

**Comment by hegemonic** [comment]
Thanks for the heads up. It looks like there's a DNS issue:

```
$ nslookup usejsdoc.org
;; Got SERVFAIL reply from 1.1.1.1, trying next server
;; Got SERVFAIL reply from 1.0.0.1, trying next server
Server:		8.8.8.8
Address:	8.8.8.8#53

** server can't find usejsdoc.org: SERVFAIL
```

I don't own the domain, though. @micmath: Any idea what's up?

**Comment by hegemonic** [comment]
I'm working on bringing the site back up on a new domain. That might take another day or so, but it will be back up soon.

**Comment by ungoldman** [comment]
ty 🙏

**Comment by hegemonic** [comment]
That went faster than expected. The site is now available at https://jsdoc.app/.

@micmath, can you please redirect all traffic from usejsdoc.org to jsdoc.app?

**Comment by molinto** [comment]
Any updates please?

**Comment by SamB** [comment]
> @micmath, can you please redirect all traffic from usejsdoc.org to https://jsdoc.app?

Hopefully this triggers a notification email for him?

**Comment by userabuser** [comment]
I'd suggest (in the meantime waiting for the redirects) generating a sitemap and submitting that to Google Search Console to get the site indexed as only a handful of pages show up and `usejsdoc.org` is still dominating the SERPs.

**Comment by oshihirii** [comment]
as a temporary workaround, any reason why it wouldn't be a good idea to edit local windows 10 `hosts` file with:

    185.199.110.153 usejsdoc.org

where `185.199.110.153` is the result of `ping jsdoc.app`.

just so that any google search results for `usejsdoc.org` actually load content from `jsdoc.app`?

when i do this, i am getting a github 404 page.  

any ideas how to remedy this?

thank you.

**Comment by TomasHubelbauer** [comment]
FYI the site is still down and Google doesn't index anything from the new site, all the queries show the old site.

**Comment by FranklinYu** [comment]
> it's on Github and hasn't been updated for 5 years so hopefully it is hunky dory privacy/security wise.

If you want something updated within a year and open-sourced, try [Redirector](http://einaregilsson.com/redirector/). It even has Firefox version.

**Comment by ithinkandicode** [comment]
+1 Some old site pages are still shown in Google. Is the original domain name still controlled?

@FranklinYu Thanks for that :) For anyone else using Redirector, get settings for jsdoc are [here](https://gist.github.com/ithinkandicode/daca53c3dbf8719588d7e008f9c784f1)

**Comment by micmath** [comment]
Sorry, I just saw this message. I've now added a redirect in with the
usejsdoc.org domain registrar. Hope that sorts it out.

**Comment by hegemonic** [comment]
Belated thanks for setting up the redirect, @micmath!
