### ISSUE TITLE
Can I parse comments, completely ignoring all code?

### ISSUE THREAD

**Issue by trusktr** [jsdoc/jsdoc#1677]
F.e., if I want to place JSDoc comments in any file (cpp, typescript, CSS), can I tell jsdoc to parse the comments, and completely ignore source (so that it does not do any inference from source code)?

I'm looking for a doc comments parser that can take my comments as the source of truth, and completely ignore all source.

**Comment by drmats** [comment]
There's a plugin for that: https://github.com/jsdoc/jsdoc/blob/master/plugins/commentsOnly.js

You need to enable it in your `jsdoc.json` file:
```
{
    "plugins": ["plugins/commentsOnly"]
}
```
