### ISSUE TITLE
Ignore the JsDocComment when hovering the API

### ISSUE THREAD

**Issue by kmuthukumar23** [jsdoc/jsdoc#1695]
As i am use the JSDoc comments in my TS source, For that i need to hide some custom comments.

Like: In source :

```typescript
     /**
     * Some string.
     * @public
     * @deprecated
     */
    public method {
         return Statements;
    }
````
Above code method is shown in the API as follows:

![image](https://user-images.githubusercontent.com/31958591/65239349-6b667000-dafc-11e9-9dc7-e00e216e65c0.png)

Here i need to hide the @deprecated in API level which means when  i am hover that API, '@deprected' comment should hide. 

Please note: Hide only when hovered tooltip content.
 
i want like this 

![hide](https://user-images.githubusercontent.com/31958591/65241668-c484d280-db01-11e9-92f9-105a68ad874a.png)

Is there any way to achieve this?

### Your environment

Node.js  :v8.11.1
npm  : 6.5.0
Operating system :![image](https://user-images.githubusercontent.com/31958591/65241898-60aed980-db02-11e9-9487-52df79f154a8.png)

**Comment by hegemonic** [comment]
VS Code does not use the JSDoc tool in this repo. Please file an issue in the appropriate VS Code repo.
