### ISSUE TITLE
Event not appearing in JSDOC Sidemenu.

### ISSUE THREAD

**Issue by divyanshu-rawat** [jsdoc/jsdoc#1713]
I have generating documentation for my Polymer 3.0 project using JSDOC.

This is how my generated sidebar looks as of now.

![docs](https://user-images.githubusercontent.com/13464678/66996248-b14d2e80-f0d0-11e9-92b4-31c5a7c7cbf3.PNG)

Name of class here it is **Clip**, followed by **members** and **methods** of the class.
So, my concern is that I also have **events** in my class, what I want is to have **events** as a sub-heading in the menu on left hand side just like we have have **methods** and **members** in it.

Nevertheless, Events are visible fine inside the broader view of a **Clip** class as shown in below attached snapshot, but they are not reflected in menu like **members** and **methods**.

![docs2](https://user-images.githubusercontent.com/13464678/66996687-74ce0280-f0d1-11e9-97a9-21e4e7de7997.png)

I tried exploring the **jsdocs** documentation but unable to found any tag that can help me to achieve the same, i.e - placing **events** as a sub-heading on menu on left hand side. 

Any help on this will be appreciated.

P.S : JSDOC Template that I am using is `boxy-jsdoc-template`.

**Comment by hegemonic** [comment]
Please file an issue in the template's repository. The only way to add content to the sidebar is to update the template.
