### ISSUE TITLE
Recursive typedef

### ISSUE THREAD

**Issue by steveswork** [jsdoc/jsdoc#1726]
I have come across several objects containing self references but cannot find anything in the documentation or anywhere about writing a proper typed documentation for them. Is this type of thing even possible?

### Input code

```js
/**
*    @typedef {{
*        key: string,
*        value?: string | Data
*    }} Data
*/
/** @type {(code: string) => Data} */
var getData = code => ({
    key: `${code}_0`,
    value: {
        key: `${code}_1`,
         value: {
            key: `${code}_2`,
            value: code
        }
    }
});
```
### Your environment

| Software         | Version
| ---------------- | -------
| JSDoc            |  3.6.3
| Node.js          | 12.9.0
| npm              | 6.10.2
| Operating system | Windows 10

**Comment by steveswork** [comment]
Can this be added as feature?

**Comment by visj** [comment]
If you replace your `@typedef` with an `@interface`, recursive type definitions work fine. Your example could be solved like this:
<details>
<summary>Show code</summary>

```js
/**
 * @interface
 */
function Data() { }

/**
 * @type {string}
 */
Data.prototype.key;

/**
 * @type {string|Data|void}
 */
Data.prototype.value;

/** 
 * @type {function(string): Data} 
 */
var getData = code => ({
  key: `${code}_0`,
  value: {
      key: `${code}_1`,
       value: {
          key: `${code}_2`,
          value: code
      }
  }
});
```
</details>

**Comment by steveswork** [comment]
My latest VS code shows that the requested feature has been added.
```
/** @type {(code: string) => Data} */
```
produces:
```
const getData: (code: string) => {
    key: string;
    value: string | ...;
}
```
which I think is more descriptive that the usual 
```
const getData: (code: string) => Data
```
PS: Thanks, @visj, for your input. I appreciated it very much.
