### ISSUE TITLE
How can I parse typescript and javascript all ?

### ISSUE THREAD

**Issue by hzk007** [jsdoc/jsdoc#1738]
hello,the jsdoc can support typescript file? I see it in the better-doc support but can not find in this, the plugin can provide later?

**Comment by SukantPal** [comment]
@hzk007 No, JSDoc doesn't support ES6 and Typescript files as of now.

At PixiJS, the solution is to compile Typescript files into a separate (temporary) directory `dist/compiled` and then run JSDoc on ES6. However, we also use `@pixi/jsdoc-template/plugins/es6-fix` to fix JSDoc problems on ES6 code.
