### ISSUE TITLE
How to declare the property of window object

### ISSUE THREAD

**Issue by RyuGuo** [jsdoc/jsdoc#1826]
How to declare the property of window object? Just like this:

```
/**
* This is a gobalData
* 
* @type{Map<string, any>} globalData
*/
window.globalData = new Map();
```

| Software         | Version
| ---------------- | -------
| JSDoc            |JSDoc 3.6.3 (Sun, 14 Jul 2019 17:01:26 GMT)
| Node.js          |v12.16.1
| npm              |6.7.0
| Operating system |Windows10

**Comment by Degubi** [comment]
Has anyone figured this one out?
I'm trying to do basically the same, but with functions:

```javascript
// I currently have this to avoid the error 'Property 'myFun' does not exist on type 'Window & typeof globalThis'' in VsCode
@param { number } msg
window['myFun'] = function(msg) {}

// I'd like this without errors
@param { number } msg
window.myFun = function(msg) {}
```

Also when trying to call an external function:

```javascript
// Property 'otherFn' does not exist on type 'Window & typeof globalThis'
window.otherFn();
```

Is there a way to declare that otherFn exists on window?

**Comment by RyuGuo** [comment]
I don't have a good idea for this, but you can try extend window module.
```javascript
class ExWindow extends Window {
  /** @param {string} msg */
  myfunc(msg) {}
}
const W = new ExWindow();
W.myfunc("as you see");
W["myfunc"]("as you see");
```

**Comment by markcellus** [comment]
Looks like this can be done now. Given the example in the original post:

```js
/**
 * @typedef {object} CustomWindowObject
 * @property {Map<string, any>} [globalData]
 */

/**
 * @typedef {Window & CustomWindowObject} CustomWindow
 */
```

Then you would just use the `CustomWindow` type anywhere you need. Hope this helps!
