### ISSUE TITLE
Does not work with django templates {% %}

### ISSUE THREAD

**Issue by iSteal** [jsdoc/jsdoc#1847]
javascript files with django template tags, such as `{% endfor %}` will result in `ERROR: Unable to parse <path>: Unexpected token`

Is there anyway to parse javascript files with template tags?

**Comment by hegemonic** [comment]
You can use the `commentsOnly` plugin to ignore everything in your source files except the JSDoc comments: https://github.com/jsdoc/jsdoc/blob/releases/4.0/plugins/commentsOnly.js

That will cause JSDoc to ignore the source code, too, which means your JSDoc comments must use the [`@name` tag](https://jsdoc.app/tags-name.html) and specify _all_ relevant information about your code.
