### ISSUE TITLE
Cannot document object with numeric string properties.

### ISSUE THREAD

**Issue by dailytabs** [jsdoc/jsdoc#1855]
This doesn't seem possible. Trying to document this argument:
```js
{
    "0": 1,
    "1": 1,
    "2": 1
}
```
Tried:
![image](https://user-images.githubusercontent.com/1219653/92824799-d6a7f280-f39c-11ea-8d0c-dc27a467f766.png)
As you can see, the foobar works, but the numbers do not. In fact, they cause the data object's type to be OR'd with number - which is **completely** wrong.
I also tried with `@param {number} data["0"]` to no avail.

I searched Google for over 15 minutes and found **absolutely** nothing regarding documenting properties that require quotes, let alone numeric strings.

**Comment by dailytabs** [comment]
Is this my only option?

```js
        /**
         * @typedef {object} ISR
         * @property {number} "0"
         * @property {number} "1"
         * @property {number} "2"
         */
        /**
         * ...
         * @param {ISR} data
         * ...
         */
```
IDE still loses any connection to those properties (takes me to the first line of the typdef's jsdoc block), but at least it's not completely wrong, anymore.

**Comment by franktopel** [comment]
What's the difference between

```
{
    "0": 1,
    "1": 1,
    "2": 1
}
```

and 

```
[ 1, 1, 1]
```
?

**Comment by dailytabs** [comment]
Wow! Lol

**Comment by The-White-Fang** [comment]
The above works in the case of an array, but there are times when you need the properties to be numeric and not like an array but with specific numbers representing some specific types. What should we do in that case?

**Comment by Gkolman** [comment]
having the same issue 

/**
 * @typedef {('X' | 'A' | 'C')} productRankIndex
 */

/**
 * @typedef {array} Rank
 * @prop {productRankIndex} 0
 * @prop {productRankIndex} 1
 * @prop {productRankIndex} 2
 * @prop {productRankIndex} 3
 * @prop {productRankIndex} 4
 * @prop {string} 0RankNumber
 * @prop {string} 1RankNumber
 * @prop {string} 2RankNumber
 * @prop {string} 3RankNumber
 * @prop {string} 4RankNumber
 */
 
Been at this for 30 minutes

**Comment by The-White-Fang** [comment]
Yep, it kinda sucks. Though if you want you can rewrite it as
```
/** @typedef {('X' | 'A' | 'C')} ProductRankIndex */

/**
 * @typedef {{
 *    0: ProductRankIndex;
 *    1: ProductRankIndex;
 *    2: ProductRankIndex;
 *    3: ProductRankIndex;
 *    4: ProductRankIndex;
 *    0RankNumber: string;
 *    1RankNumber: string;
 *    2RankNumber: string;
 *    3RankNumber: string;
 *    4RankNumber: string;
 * }} Rank
 */
``` 

The only disadvantage of this is that now you cannot add helpful comments about the properties you are adding. This is a bit annoying especially if you are working with something similar to `GravityForms` since the object properties are just random numbers and you need those comments to know what each field means.
