### ISSUE TITLE
Unable to follow complex export blocks

### ISSUE THREAD

**Issue by y-nk** [jsdoc/jsdoc#1858]
### Input code

```js
/** @module myModule */

export {
  default as SomePropName,
  SomeOtherExport1,
  SomeOtherExport2,
} from './someOtherFile'
```

### Expected behavior

I should see SomePropName, SomeOtherExport1 and SomeOtherExport2 (with proper typings) as member of myModule

### Current behavior

I see nothing

### Your environment

| Software         | Version
| ---------------- | -------
| JSDoc            | latest
| Node.js          | latest
| npm              | latest
| Operating system | macOS

**Comment by Twipped** [comment]
I'm also having this struggle, I cannot seem to figure out how to define a named export at all.

**Comment by y-nk** [comment]
@Twipped looking at the state of this repo i'm afraid we're left with no solution. good luck 👌
