### ISSUE TITLE
How to add multiple ES6 mixins?

### ISSUE THREAD

**Issue by JosefJezek** [jsdoc/jsdoc#1872]
> How do u add multiple mixins? So my code looks like:
> 
> ```js
> const Mixin1 = (superclass) => class extends superclass {} 
> 
> const Mixin2 = (superclass) => class extends superclass {} 
> 
> class A extends Mixin1(Mixin2(SomeBaseClass)) {}
> ```
> 
> but VSCode intellisense can recognize the Mixin1 docs only. Do u have any suggestions for this problem?

+1

How do I get intellisense to recognize, in this case, Mixin2 and SomeBaseClass's members?

_Originally posted by @manix in https://github.com/jsdoc/jsdoc/issues/1409#issuecomment-716442196_

**Comment by manix** [comment]
I opened an issue for this over at vscode and they moved it to typescript

https://github.com/microsoft/TypeScript/issues/41256

**Comment by hegemonic** [comment]
This repo has no relationship with VS Code.
