### ISSUE TITLE
Cant parse Expression "||=" ?

### ISSUE THREAD

**Issue by hexxone** [jsdoc/jsdoc#1904]
### Input code

CComponent.ts:
```js
	/**
	* will recursively try to set a setting with type and return success
	* will also flag the module as needs-Update.
	*
	* @param {Object} key
	* @param {Object} value
	* @return {boolean} found
	*/
	public applySetting(key: any, value: any): boolean {
		let found = this.settings.apply(key, value);
		if (found) {
			this.needsUpdate = true;
			Smallog.debug(`ApplySetting: ${key}:${value}`);
		}
		this.children.forEach((ch) => found ||= ch.applySetting(key, value)); // <--- Here is the problem " ||= "
		return found;
	}

```

### JSDoc configuration

```js
{
	"opts": {
		"template": "./../../node_modules/better-docs",
		"encoding": "utf8",
		"destination": "./docs/",
		"recurse": true,
		"readme": "./README.md"
	},
	"plugins": [
		"./../../node_modules/better-docs/typescript"
	],
	"recurseDepth": 10,
	"source": {
		"include": ["./src"],
		"exclude": ["./src/wasc-worker/node_modules"],
		"includePattern": ".+\\.(jsx|js|tsx|ts)$",
		"excludePattern": "(^|\\/|\\\\)_"
	},
	"tags": {
		"allowUnknownTags": true,
		"dictionaries": ["jsdoc","closure"]
	}
}

```

### JSDoc debug output

```
Parsing D:\...\src\CComponent.ts ...
ERROR: Unable to parse D:\...\src\CComponent.ts: Unexpected token (27:47)
```

### Expected behavior

Should normally parse the function documentation... and not break from the logic/operator?

### Current behavior

The operator "||=" seems to be an "unexpected token" for jsDoc and will skip the doc generation for the whole file...

Commenting the line out with "//" causes the file to be processed correctly.

Even though it is syntactiacally correct:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR_assignment

I'm really surprised that I didnt find an issue reagrding this already?

I hope this is the right place for the issue, and not caused by  "better-docs"? :)

Thanks in advance!

### Your environment

| Software         | Version
| ---------------- | -------
| JSDoc            | JSDoc 3.6.6 (Sun, 20 Sep 2020 02:25:14 GMT)
| Node.js          | v14.15.5
| npm              |  6.14.11
| Operating system | Win10 latest updates

**Comment by ajvincent** [comment]
Peanut gallery observation: Maybe it's your node version.  At the bottom of the DevMo page, it shows this operator isn't supported until Node 15.

OTOH, you're working with TypeScript, and all I know is that it transpiles to JavaScript.
