### ISSUE TITLE
Maintenance inquiry, from the package maintenance team

### ISSUE THREAD

**Issue by ghinks** [jsdoc/jsdoc#1910]
This is an enquiry and question to @hegemonic about the current maintenance of the JSDocs module(s). 

Do you require assistance with maintenance? I have been asked to make an enquiry about the current status of this project.

**Comment by mikicho** [comment]
I'm thinking about going back from typescript to plain js (I want to skip the build and use `tsc` only for type-checking).
I want to join my friend's question.

I'd love see this project evolve, do you need any help?
One of the things that missing for me is to be able set type parameters like:

```
type A<B> = {
   a: B
}

const a: A<string> = {
   a: 'a'
}
```
