### ISSUE TITLE
How do I exclude namespaced classes that should very much never be in the main nav, from the main nav?

### ISSUE THREAD

**Issue by Pomax** [jsdoc/jsdoc#1946]
I have an `Errors` module which exports about 30 `class Something extends Error` that lead to the worst documentation pollution if they're included in the "classes" section in of the nav:

> ![image](https://user-images.githubusercontent.com/177243/137600629-c06da51b-f291-4bcf-92af-bd3a86daff2e.png)

These classes should only ever show up on the `Errrors` namespace page, so: what (combination of) keywords make that happen?

I've been trying the most ridiculous combinations just in the hopes that it'll trick jsdoc into doing the right thing, but nothing seems to work, and have the docs be a hot mess of LOTS_OF_ERROR_CLASS_NAMES that make it impossible to see which _actual_ classes exist is not great.

**Comment by staticBanter** [comment]
Have you tried using the `@private` tag? According to the documentation:

> The `@private` tag marks a symbol as private, or not meant for general use. Private members are not shown in the generated output unless JSDoc is run with the -p/--private command-line option.

**Comment by Pomax** [comment]
The problem is that these are symbols that *are* meant for general use - they are exported as constants for use in error comparisons, so I want there to be jsdocs for them, but I also want them captured in, for instance, a heading like "errors" rather than having every single one listed in the main nav.

**Comment by staticBanter** [comment]
My apologies I misinterpreted the outcome that you desired, you still need them documented but you only want them to be associated with the *Error* namespace. I would try the `memberOf` keyword:

> In the following example, the `hammer` function would normally be documented as a global function. That's because, in fact, it is a global function, but it is also a member of the `Tools` namespace, and that's how you wish to document it. The solution is to add a `memberof` tag:

https://jsdoc.app/tags-memberof.html

**Comment by Pomax** [comment]
that did the trick, thanks!
