### ISSUE TITLE
High severity vulnerability security advisory for a dependency, `marked`

### ISSUE THREAD

**Issue by JJ** [jsdoc/jsdoc#1965]
Which is, apparently, no longer in the repo. I guess that, along #1964, just releasing what's in `main` will take care of it.
TL;DR: Upgrade it to 4.0.10 or better https://github.com/advisories/GHSA-rrrm-qjm4-v8hf
Related: #1413. Although it's been removed, there does not seem to be a commit that references it.

**Comment by kuroky360** [comment]
The latest version of the library is 3.6.7 and the marked vulnerability is still present, can you release a new version with the marked vulnerability removed?

**Comment by anneliseschulzz** [comment]
Any idea of when the new version is going to be released? 
We can't go on with jsdoc in production until the vulnerabilities are removed

**Comment by JJ** [comment]
I'm not sure this is actively developed any more. I wonder if anyone would be interested in forking and releasing a new version? Initially just with vulnerabilities fixed, then we'll see?

**Comment by hegemonic** [comment]
Fixed in JSDoc 3.6.8.
