### ISSUE TITLE
Back to top thing on jsdoc.org is very annoying

### ISSUE THREAD

**Issue by eldoy** [jsdoc/jsdoc#1992]
The "back to top" widget on the right of the usejsdoc.org web site is very annoying. Every time you start reading something and scroll down it catches your eye when it's moving and distracts you, for every single page you visit. It also happens when you scroll up again. Using red makes it seem like something very important, which it is not IMO and is not really good UX.

Fix: It should not be moving at all and should have a less distracting color.

**Comment by hegemonic** [comment]
We don't own the `jsdoc.org` domain, and it appears that the website at that domain no longer exists.
