### ISSUE TITLE
Dead link in wiki

### ISSUE THREAD

**Issue by jadedrakerider** [jsdoc/jsdoc#2003]
In the [wiki](https://github.com/jsdoc/jsdoc/wiki) of this repository, there is a link to instructions on how to use jsdoc. [This link](http://www.usejsdoc.org/?from=@) appears dead.

**Comment by Infinixius** [comment]
The new link is [https://jsdoc.app/](https://jsdoc.app/).

**Comment by paulkre** [comment]
The new link is down
