### ISSUE TITLE
How do I actually use JSDoc?

### ISSUE THREAD

**Issue by jadedrakerider** [jsdoc/jsdoc#2004]
First, I want to apologize for asking such a basic question. I am not a professional developer and I have very little professional coding experience (small scripts for websites), but I am interested in picking up these skills. I want to introduce JSDoc to a project at work that I think would be beneficial for our entire team, but first I need to try it and be able to demo it. So I figured I would start a project demoing setup and usage. You can find the files I am working with in [this repository](https://github.com/jadedrakerider/JSDoc-Tutorial).

I have read:
[Getting Started with JSDoc 3](https://jsdoc.app/about-getting-started.html)
[Using namepaths with JSDoc 3](https://jsdoc.app/about-namepaths.html)
[Configuring JSDoc with a configuration file](https://jsdoc.app/about-configuring-jsdoc.html)

So the question is, how do I get this to output documentation .HTML file(s)? I must be doing something wrong but I am missing something or I am not remembering something I read. This is _not_ a bug, this is a user's error.

### Input code

I have two scripts inside `./scripts/`

`script.js`
```js
/*
  @description
  title: A Title 
  file: script.js
  This is the description of the script.js file, which is the main 
  code file that calls other *.js files. 
*/

/*
  @todo Finish the HTML document
*/

// @todo fill the Elements object
const Elements = {};

// @todo fill the Listeners object
const Listeners = {};

// @todo fill the Functions object
const Functions = {};
```

`another.js`
```js
// @description testing recursive file search
```

In the VS Code application is a terminal, I have tried using

```
location: .jsdoc-tutorial
```

```
$ jsdoc -c ./out/conf/conf.json ./scripts/
```

`location: ./jsdoc-tutorial/out`

```
$ jsdoc -c ./conf/conf.json ../scripts/
```

### JSDoc configuration

I have a configuration file at `./out/conf/conf.json`

```js

{
  "tags": {
    "allowUnknownTags": true,
    "dictionaries": ["jsdoc", "closure"]
  },
  "source": {
    "includePattern": ".+\\.js(doc|x)?$",
    "excludePattern": "(^|\\/|\\\\)_"
  },
  "sourceType": "module",
  "plugins": ["plugins/markdown", "plugins/summarize"],
  "opts": {
    "template": "templates/default",  // same as -t templates/default
    "encoding": "utf8",               // same as -e utf8
    "destination": "./out/",          // same as -d ./out/
    "recurse": true//,                // same as -r
//  "tutorials": ""                   // same as -u path/to/tutorials
},
  "templates": {
    "cleverLinks": false,
    "monospaceLinks": false,
    "default": {
      "outputSourceFiles": true
    },
    "source": {
      /* array of paths to files to generate documentation for */
      "include": ["./scripts/script.js"],
      /* array of paths to exclude */
      "exclude": [],
      "includePattern": ".+\\.js(doc|x)?$",
      "excludePattern": "(^|\\/|\\\\)_"
    }
  }
}
```

### JSDoc debug output

It looks. like jsdoc sees my js files above ...

```
DEBUG: JSDoc 3.6.11 (Wed, 20 Jul 2022 17:40:43 GMT)
DEBUG: Environment info: {"env":{"conf":{"plugins":["plugins/markdown","plugins/summarize"],"recurseDepth":10,"source":{"includePattern":".+\\.js(doc|x)?$","excludePattern":"(^|\\/|\\\\)_"},"sourceType":"module","tags":{"allowUnknownTags":true,"dictionaries":["jsdoc","closure"]},"templates":{"monospaceLinks":false,"cleverLinks":false,"default":{"outputSourceFiles":true},"source":{"include":["./scripts/script.js"],"exclude":[],"includePattern":".+\\.js(doc|x)?$","excludePattern":"(^|\\/|\\\\)_"}},"opts":{"template":"templates/default","encoding":"utf8","destination":"./out/","recurse":true}},"opts":{"_":["./scripts/"],"configure":"./out/conf/conf.json","recurse":true,"debug":true,"template":"templates/default","encoding":"utf8","destination":"./out/"}}}
DEBUG: Parsing source files: ["~/Workspace/JSDoc-Tutorial/scripts/another.js","`/Workspace/JSDoc-Tutorial/scripts/script.js"]
Parsing ~/Workspace/JSDoc-Tutorial/scripts/another.js ...
Parsing ~/Workspace/JSDoc-Tutorial/scripts/script.js ...
DEBUG: Finished parsing source files.
DEBUG: Adding inherited symbols, mixins, and interface implementations...
DEBUG: Adding borrowed doclets...
DEBUG: Post-processing complete.
Generating output files...
Finished running in 0.30 seconds.
```

### Expected behavior

My `./out/index.html` file should have documentation or links to documentation pages created by jsdoc.

### Current behavior

My `./out/index.html` [contains very little](https://github.com/jadedrakerider/JSDoc-Tutorial/blob/main/out/index.html).

This is what it renders:
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/7771951/180811515-4bc1b97f-4a4a-4f62-911a-a82b0642bc08.png">

### Your environment

| Software         | Version |
| ---------------- | ------- |
| JSDoc            | JSDoc 3.6.11 |
| Node.js          | v14.17.5 |
| npm              | 8.15.0 |
| Operating system | macOS 12.4 |

### Thanks
Thank you for taking the time to read this.

**Comment by Infinixius** [comment]
JSDoc comments use `/** */` instead of `/* */`.

To fix your examples:
```js
/**
 * @description
 * title: A Title 
 * file: script.js
 * This is the description of the script.js file, which is the main 
 * code file that calls other *.js files. 
*/

/**
  @todo Finish the HTML document
*/

/** @todo fill the Elements object */
const Elements = {};

/** @todo fill the Listeners object */
const Listeners = {};

/** @todo fill the Functions object */
const Functions = {};
```

```js
/** @description testing recursive file search */
```

**Comment by GeorgeSchafer** [comment]
@Infinixius Jadedrakerider here. Thanks! This is definitely going into my demo. Thank you so much for answering.

**Comment by webketje** [comment]
Motion to close. Question has been answered
