### ISSUE TITLE
Latest version much ahead of main branch

### ISSUE THREAD

**Issue by remino** [jsdoc/jsdoc#2011]
When I install jsdoc now using npm, I get 3.6.11.

But I see on GitHub, the last published release was 3.5.5 dated two years ago. I also noticed the 3.6.11 tag in the repo is far ahead of the main branch, which also refers to the 3.5.5 release.

Can main be updated? Which branch should I use for development?

**Comment by hegemonic** [comment]
After 3.5.5, I neglected to convert the Git [tags](https://github.com/jsdoc/jsdoc/tags) for each version into GitHub "releases." I need to backfill those at some point.

JSDoc development happens on the `main` branch; releases happen off of release branches. For example, 3.6.11 was released off of the [`releases/3.6` branch](https://github.com/jsdoc/jsdoc/tree/releases/3.6).

The `main` branch is, in fact, far ahead of the `releases/3.6` branch; as of right now, GitHub says the `releases/3.6` branch is "26 commits ahead, 531 commits behind `main`." On `main`, I'm working (very, very, _very_ slowly) on modernizing and reorganizing JSDoc's code. It's a moving target, but a very slow-moving target.
