### ISSUE TITLE
taffydb - Internal Property Tampering

### ISSUE THREAD

**Issue by Tony4469** [jsdoc/jsdoc#2019]
[taffydb](https://www.npmjs.com/package/taffydb) is an open source JavaScript library that provides in-memory database capabilities

Affected versions of this package are vulnerable to Internal Property Tampering. taffy sets an internal index for each data item in its DB. However, it is found that the internal index can be forged by adding additional properties into user-input. If an index is found in the query, taffyDB will ignore other query conditions and directly return the indexed data item. Moreover, the internal index is in an easily-guessable format (e.g. T000002R000001). As such, attackers can use this vulnerability to access any data items in the DB.

Note: The taffy package has been deprecated by the author. Its successor package, taffydb, is also found to be vulnerable and is not actively maintained.

**Comment by hegemonic** [comment]
As of version 4.0.0, JSDoc no longer uses the `taffydb` package. Please upgrade to version 4.0.0.
