### ISSUE TITLE
This experimental syntax requires enabling the parser plugin: "importAssertions"

### ISSUE THREAD

**Issue by 75lb** [jsdoc/jsdoc#2039]
Clone this [reproduction gist](https://gist.github.com/75lb/361808f5fc802681157bd7366a693ce1) then run `jsdoc index.js`. You get this error message: 

```
$ jsdoc index.js
ERROR: Unable to parse import-assertions/index.js: This experimental syntax requires enabling the parser plugin: "importAssertions". (1:31)
```

What is the recommended way to resolve this issue?

**Comment by hegemonic** [comment]
Thanks for the heads up! I just published JSDoc 4.0.2, which upgrades the Babel parser and enables support for this ECMAScript syntax proposal (plus a bunch more). Your example should work in JSDoc 4.0.2.
