### ISSUE TITLE
TaffyDB can allow access to any data items in the DB

### ISSUE THREAD

**Issue by rmlevangelio** [jsdoc/jsdoc#2041]
Looks like TaffyDB is a direct dependency of this package. Dependabot is complaining about TaffyDB.

<img width="911" alt="image" src="https://user-images.githubusercontent.com/7041900/222136239-4f300c9c-0a0d-4a89-a665-8583fe0f40dc.png">

### Your environment

| Software         | Version |
| ---------------- | ------- |
| JSDoc            | latest
| Node.js          |
| npm              |
| Operating system |

**Comment by Syed-Ali-Abbas-Zaidi** [comment]
Hi @hegemonic! when will these changes be published on npm? Our project has the same dependabot alert due to indirect dependency on taffydb.

**Comment by hegemonic** [comment]
Upgrade to JSDoc 4.0.0 or later. These version no longer use TaffyDB.
