### ISSUE TITLE
“The type 'ShadowRootMode' is undefined”

### ISSUE THREAD

**Issue by Hibou57** [jsdoc/jsdoc#2043]
### Input code

```js
  /** @interface ShadowRootInit */
  const options = {
    /** @type {ShadowRootMode} */
    mode: 'closed',
    delegatesFocus: true,
  };
```

### JSDoc configuration

```js
    "jsdoc": {
      "mode": "typescript",
      "structuredTags": {
        "template": {
          "name": "namepath-defining",
          "required": "name",
          "type": "false"
        }
      },
      "tagNamePreference": {
        "augments": "extends",
        "constant": "const",
        "description": false,
        "file": "overview",
        "fires": "emits"
      }
    }
```

### JSDoc debug output

Not applicable: JSDoc used in conjunction with ESlint, for comments and types checking only, not for documentation generation.

### Expected behavior

The type `ShadowRootMode` should be visible.

### Current behavior

It complains the type `ShadowRootMode` is undefined.

### Your environment

| Software         | Version |
| ---------------- | ------- |
| JSDoc            | eslint-plugin-jsdoc@40.0.0
| Node.js          | v18.14.2
| npm              | 9.5.0
| Operating system | Ubuntu 20.04

### Personal investigations

The definition of the type is in `node_modules/typescript/lib/lib.dom.d.ts` and is `type ShadowRootMode = "open" | "closed";`. Surprisingly, if `"closed"` is changed to `"closed2"` or the `"closed"` alternative is removed, the type becomes visible. Alternatively, if a `type Foo = "open" | "closed";` is added, then this type is not visible neither. JSDoc seems to have an issue with this particular enumeration, especially with the `"closed"` enumerated value.

**Comment by Hibou57** [comment]
So far, the only work around seems to edit `lib.dom.d.ts`, and change the definition

    interface ShadowRootInit {
        delegatesFocus?: boolean;
        mode: ShadowRootMode;
        slotAssignment?: SlotAssignmentMode;
    }

into

    interface ShadowRootInit {
        delegatesFocus?: boolean;
        mode: string; // BUG: should be ShadowRootMode
        slotAssignment?: SlotAssignmentMode;
    }

Without this, there is no way to be able to use `Element.attachShadow`.

**Comment by Hibou57** [comment]
Issue closed by error, sorry.

**Comment by hegemonic** [comment]
This issue tracker is for the `jsdoc` tool and the code in this repo, not for any issue that involves JSDoc tags or type-checking. And the `eslint-plugin-jsdoc` plugin doesn't use any code from this repo; see its [dependency graph](https://npmgraph.js.org/?q=eslint-plugin-jsdoc).

Please file a bug for `eslint-plugin-jsdoc` instead.
