### ISSUE TITLE
jsdoc package vulnerable to HTML injections

### ISSUE THREAD

**Issue by divysts** [jsdoc/jsdoc#2073]
```org.webjars.npm_jsdoc``` package from all versions are vulnerable for HTML injection. It is possible to inject HTML content in the comments before the code being documented. Once code is commented and jsdoc was used to generate HTML website from the sourcefiles, accessing webpage where HTML was injected in comments will show the actual element. This issue allows page modification through the comments and expose the user for different vulnerabilities such as Cross-Site Scripting (XSS).

During our security scan this vulnerability was discovered in jsdoc. Please see through this

**Comment by hegemonic** [comment]
Duplicate of https://github.com/jsdoc/jsdoc/issues/1991, which explains why this isn't a "vulnerability" in any meaningful sense.
