### ISSUE TITLE
No Pretty Printed Source?

### ISSUE THREAD

**Issue by matthewkastor** [jsdoc/jsdoc#208]
JsDoc Toolkit produced copies of the source files with syntax highlighting and line numbers. Then put links in the documentation to the pretty sources. Jsdoc 3 puts notes about which source file a specific item was documented from but, there are no links and no pretty sources. Has this feature been dropped or is it just broken? I really liked having the source referenced and prettied up for the docs.

**Comment by leegee** [comment]
`templates.default.outputSourceFiles: false` still leaves a massive JavaScript file at the top of what I'd hoped would be my documentation file.  Should I create a new report?

    $ ../../node_modules/.bin/jsdoc --version
    JSDoc 3.4.0 (Tue, 10 Nov 2015 00:28:09 GMT)

**Comment by matthewkastor** [comment]
Make a new issue. This was closed years ago.
