### ISSUE TITLE
'jsdocCommentFound' event in plugins doesn't actually pay attention to comment changes.

### ISSUE THREAD

**Issue by mathematicalcoffee** [jsdoc/jsdoc#228]
The documentation for `jsdocCommentFound` in the readme suggests that you can use this event to modify
the contents of a comment before it is parsed.

Based on this, I made a plugin to add '@const' to every comment found (just a toy example, don't worry, wouldn't actually do it):

```
exports.handlers = {              
    jsdocCommentFound: function (e) {    
            // e.filename, e.comment, e.lineno 
            // replace the last `*/` with `@const */`
            e.comment = e.comment.replace(/\s*\*\/\s*$/, '\n@const\n*/'); 
            console.log(e.comment);
    }    
}
```

On a test file:

```
/** constant asdf */                                                            
const asdf = 'asdf';                                                            
/** constant fdsa */                                                            
const fdsa = 'fdsa';                                                            
```

This outputs the (modified) comments:

```
/** constant asdf
@const
*/
/** constant fdsa
@const
*/
```

so I know that the comment is being modified correctly.
## Expected output

the doclets have `kind` set to `constant` and are documented as so (default template), as the modified comments are then fed in to the parser.
## Actual output

the doclets have `kind` set to `member` and as such are not documented as constants.
## Fix?

Either:
- `jsdocCommentFound` event does not let you modify `e.comment` to modify a comment before it is parsed; then remove the documentation (from plugins/README.md) suggesting this can be done;
- or, the (potentially modified) object `e` should be used when the event is fired to update the comment.

Or - how could I modify a comment's text before it gets parsed into a doclet? the `fileBegin` method is a bit too broad for me - I really need a per-doclet event.

**Comment by gesa** [comment]
Hiya @hegemonic & friends, so sorry to resurrect such an ancient issue, but I do believe there's been a regression here. Using jsdoc@3.6.3, I can recreate the issue using the original test case. 

Incidentally, I originally ran into this problem by following the documentation for plugins. The text is clearly being modified during parsing, as the console logging shows. The output file, however, does not reflect those changes.

I'll never get those four hours back, but hopefully my loss is someone else's gain and this regression can be fixed up!

(ps using identical functions for both the `jsdocCommentFound` event and the `symbolFound` event is no longer an effective workaround)
