### ISSUE TITLE
Configuration file: cannot set destination path

### ISSUE THREAD

**Issue by andrejpavlovic** [jsdoc/jsdoc#252]
When setting the destination path in conf.json, it is always overwritten to "./out/" - even when no --destination flag is used.

``` javascript
{
    "opts": {
        "destination": "./doc/"
    }
}
```

The problem seems to be that the 'destination' is always set in the command-line options, even when the flag is not specified:

See rhino_modules/jsdoc/opts/parser.js

``` javascript
var argParser = new common.args.ArgParser(),
    ourOptions,
    defaults = {
        destination: './out/'
    };
```

This default should probably be set elsewhere.

**Comment by Droogans** [comment]
I'm still getting this with `JSDoc 3.3.3 (Tue, 22 Sep 2015 23:14:17 GMT)`.

My conf specifies

```js
    "destination": "./docs/",
```

And my command line usage is

```
jsdoc -c jsdoc.conf.json
```

It is only creating `out` in the root of my project. It works when switching my command to

```
jsdoc -c jsdoc.conf.js -d docs/
```
