### ISSUE TITLE
Generating a method summary

### ISSUE THREAD

**Issue by kpturner** [jsdoc/jsdoc#296]
Not really an issue - more of a support question. How does one generate a method summary for each class as they have done here:
http://www.lightstreamer.com/docs/client_javascript_uni_api/LightstreamerClient.html
It shows a method summary section followed by a method detail section (which I can already do).

They also have a proper index:
http://www.lightstreamer.com/docs/client_javascript_uni_api/index-all.html

How do I generate that? I cannot find anything relevant in the documentation.

**Comment by maelcaldas** [comment]
Any update about that? It's pretty painful to use a library documentation without a method summary...

**Comment by hegemonic** [comment]
@maelcaldas You can try the preview version of the [Baseline template](https://github.com/hegemonic/jsdoc-baseline/), which includes method summaries.

**Comment by kpturner** [comment]
I tried using jsdoc-baseline but in my case it just seemed to hang forever without putting any content at all in the target folder :(

Difficult to tell why because it didn't produce any errors either.

**Comment by hegemonic** [comment]
@kpturner Please [file a bug against Baseline](https://github.com/hegemonic/jsdoc-baseline/issues). Before you do that, can you try running JSDoc (and Baseline) with the `--debug` option? That should give you an idea where the process is hanging.

**Comment by kpturner** [comment]
The problem appears to be with the generation of the page that shows the source of the JS file.  One or two of the files are very large.   If I omit the largest one it does eventually finish (500 seconds).  If I click on any of the source links it also takes quite a while to render.  

I wanted to try generating without the source links like this:
"sourceFiles": {
        // Set to `true` to generate pretty-printed HTML versions of the source files, and to link to
        // the pretty-printed files from the documentation. Set to `false` to omit the pretty-printed
        // source files and the links to these files.
        "generate": false,
        // Set to `true` to include a single link to the source file in the documentation, near the
        // top of the page. Set to `false` to include a source-file link with each symbol in the
        // documentation.
        "singleLink": false
    }

but that made no difference at all. It still generated the source links etc.  I must be misunderstanding this section of the config.

As an aside, I cannot understand the description of "singleLink" at all.  What is the effect of this option?
