### ISSUE TITLE
Need More robust ways to exclude multiple directories, paths, and/or files

### ISSUE THREAD

**Issue by joshrhoades** [jsdoc/jsdoc#300]
./jsdoc --help shows no way to set ignore of directories, whereas jsdoc-toolkit provided for the -nocode flag (only documenting anything with an @name, though I didn't find this as useful as the ability to ignore directories, or at the very least set a recursion depth (though, again, recursion depth is more useful if you can set explicit directories/paths to ignore)).

I keep getting `java.lang.OutOfMemoryError: Java heap space` errors when running against an entire solution (on a latest gen MBP that is maxed out), since there is a lot to recurse in the entire solution (some of which I want to flat out ignore, such as 3rd party libraries). The addition of this ability would add a lot of flexibility...unless I'm missing something in --help or the sparse documentation that provides for this.

The excludePattern handles this somewhat, but its more problematic for multiple directories, files, and/or patterns to exclude.

**Comment by heyandresdjc** [comment]
care to share the solution thanks
