### ISSUE TITLE
using JsDoc in the browser

### ISSUE THREAD

**Issue by greggman** [jsdoc/jsdoc#309]
I'm guessing this question has been asked before and is somewhat related to running in node.js but I thought I'd ask.

How much work would you estimate to get this running 100% in standard browser based JavaScript. I'm imagining something along the lines of

```
<script src="jsdoc.js"></script>
<script>
var urls = [
  'path/to/somefile.js',
  'path/to/someotherfile.js',
  'path/to/yetanotherfile.js',
];
JsDoc.generateDocs(urls);
</script>
```

Would that be a ton of work? I read some note that you're counting on Rhino to do the parsing. Apparently JSLint, UglifyJS are JavaScript parses written in JavaScript. No idea if they have the required features.

Sorry for such a blue sky question I just thought I'd ask.

**Comment by matyasf** [comment]
Any change about this issue during the last 8 years? Is it possible now to use jsDoc purely in the browser (= no Node APIs, the input is a String)
