### ISSUE TITLE
Don't hash filenames in template output

### ISSUE THREAD

**Issue by israels** [jsdoc/jsdoc#339]
I have a class defined within a RequireJS module.  Everything works as expected as long as I let jsdoc interpret the class name based on the code function.  However, one annoyance with this is the generated html file is a random string.  The only way to know what class is associated with that file is through the index.html.

My code looks like this:

``` javascript
/**
 * Test Module
 * @module test/module
 */
define( 'test/module' , function( isFunction ){

    /**
     * My Class 
     * @constructor
     * @param {Number} param1 The first param
     * @param {String} param2 The second param
     */
    Class = function( param1, param2 ){ ... };
```

Using this style of code I get a module, with a link to the class.  In turn, the class can link back to it's containing module.

<b>Problem:</b>
When I then try and name the constructor/class like so (with a constructor name):

``` javascript
    /**
     * My Class 
     * @constructor MyClassName
     * @param {Number} param1 The first param
     * @param {String} param2 The second param
     */
    Class = function( param1, param2 ){ ... };
```

It will create a file called MyClassName.html, but the module no longer documents a class contained within it and the class itself has no documentation of it being contained within the module.

I would like to be able to control readable file names for the html files.  Naming the classes seems to be the way to do this, but unfortunately appears to be breaking the parser.

**Comment by ElfenLiedGH** [comment]
hash or human-readable should be options, with russian filename it too long

srv/classes/base/ar/Аутентификация.аутентификацияНаSqlСервере 

it's some like this

%D0%9F%D0%BE%D0%B8%D1%81%D0%BA%D0%9D%D0%9F%D1%83%D0%BD%D0%BA%D1%82%D0%B0%D0%94%D0%BB%D1%8F%D0%97%D0%B2%D0%BE%D0%BD%D0%BE%D0%BA%D0%BE%D0%B2%D0%BE%D0%B3%D0%BE%D0%A6%D0%B5%D0%BD%D1%82%D1%80%D0%B0

sevral letter more and we have windows system error
