### ISSUE TITLE
Object.<string,*> seems confusing.

### ISSUE THREAD

**Issue by jnewman** [jsdoc/jsdoc#426]
In the JSDoc [types table](http://usejsdoc.org/tags-type.html#jsdoc-types) I don't understand   having e.g.:  

```
{Object.<string, number>}
```

All objects in JS are keyed by strings, unless they're Arrays. Is this somehow related to features coming in ES6?

**Comment by donquixote** [comment]
> Adding a new type-expression syntax to JSDoc is no guarantee that your IDE vendor of choice will choose to support that syntax.

From my time spent in the PhpStorm issue queue, I am quite convinced that IDE developers look at projects like this one for guidance. Of course not everything gets implemented immediately, but feature requests have a better chance if they can point to an example from the outside world.

**Comment by donquixote** [comment]
One more idea I have is `type_expression{}`. Not sure if this conflicts with anything..

```js
/**
 * @type string{}
 */
let colors = {
  red: '#ff0000',
  green: '#00ff00'
}
```

bq. A bigger concern, which I chose to omit from my last comment, is that I don't want JSDoc to end up with a bunch of obscure type-expression syntaxes that have no meaning outside of JSDoc. I'm also not interested in leading the charge to come up with a different type-expression syntax. Even if I was, I don't think that incrementally adding stuff to JSDoc is a good way to make that happen.

Sad :(

I am not familiar enough with the Javascript world to see where such innovation could happen if not here. But it has not happened yet, it seems..
