### ISSUE TITLE
Issue with documenting subclassed methods

### ISSUE THREAD

**Issue by alphanull** [jsdoc/jsdoc#434]
Let's assume I have defined a superclass and a subclass which inherits some methods and members of the superclass. (It should not matter if that is done via `@class` or `@module` / `@exports`). These methods / members are already documented in the superclass, some of them might be also tagged as `@abstract` and therefore act like a kind of interface definition. As for the subclass, I would now expect the following behavior when documenting:
1. The subclass provides **no same-named** method / member at all: the subclass gets the **superclass's documentation** (also _includes_ the `@abstract` tag, if that was provided by the superclass)
2. The subclass provides an **undocumented method** or member of the same name: the subclass gets the **superclass's documentation** (but _without_ the `@abstract` tag, if that was provided by the superclass).
3. The subclass provides a **documented** method or member of the same name: the subclass gets its **own documentation** as defined in the subclass tags.

Actually, 1) and 3) work as expected right now, but in case of 2), the superclass documentation is _not_ taken over, so the superclass method / member effectly cannot be seen anymore in the subclass documentation.

As for `@abstract`, I am not sure if the expected behavior is just masked by the issue I described above, but in essence, the `@abstract` tag should go away in the subclass documentation (but the rest of the superclass docs should be still used!), **if** you redefine the method in a subclass, but add no own documentation to it. Also, if you do _not_ define such an abstract method (or only do it in another subsubclass), the `<virtual>` output should remain.

A stripped down example to show this missing "doc inheritance" can be seen here: https://gist.github.com/micmath/5730364

**Comment by mercmobily** [comment]
Both #53 and #375 are now closed. Does this mean that this is also now fixed?

**Comment by alphanull** [comment]
It now works better since Subclass methods (and I guess members as well) now correctly inherit the docs from the Superclass (if not explicitly overriding them). So my case 2) outlined above seems to be solved. 

However, if I mark some method in the Superclass as @abstract, this method is tagged with "abstract" in the Subclass docs as well. This is something I still would not expect, since the method on the subclass is not abstract anymore.

So I would say, the more important part (at least for me) is finally fixed, but still not everything perfect in my eyes.
