### ISSUE TITLE
Create a template for generating TypeScript type definition files

### ISSUE THREAD

**Issue by hegemonic** [jsdoc/jsdoc#437]
JSDoc gathers a lot of type information when it parses code (and comments). As a result, it should be possible to generate a [TypeScript definition file](//github.com/borisyankov/DefinitelyTyped) for a given collection of source files.

That, in turn, should make it possible to create [JSON type definition files](http://ternjs.net/doc/manual.html#typedef) for [Tern](http://ternjs.net/), because Tern [includes code to convert TypeScript definition files](//github.com/marijnh/tern/blob/c049fcf9/lib/typescript.js).

**Comment by raysuelzer** [comment]
This is a great idea....

**Comment by englercj** [comment]
I'm working on a jsdoc template that does just this:

https://github.com/englercj/jsdoc2tsd

PR's welcome!

**Comment by michaeljota** [comment]
I'm working on this. I'll add the PR. :).
