### ISSUE TITLE
Inner functions and classes not part of the generated output

### ISSUE THREAD

**Issue by rraziel** [jsdoc/jsdoc#442]
Hello,

Quick snippet:

``` javascript
(function(ns) {
/** @constructor */
function Lala() {

}

/** some Lala member */
function isLala() {
}

ns.isLala = Lala.methods({
    isLala: isLala
});

})(window);
```

All our (numerous) .js files are declared this way, is there any way to make jsdoc "find" them or to do things manually for jsdoc with some extra markup ?

**Comment by tetreault** [comment]
Blows my mind that this still is an issue in 2015

**Comment by tetreault** [comment]
blows my mind this is still an issue in 2015...
