### ISSUE TITLE
Using a config file seems to exclude source code

### ISSUE THREAD

**Issue by chtulhu6662000** [jsdoc/jsdoc#454]
using this config file:
{
    "source": {
        "include": ["../sources/webstorm/server/modules"]
    },
    "opts": {
        "destination": "./api",
        "recurse": true
    }
}

doesn't produce the same result as using this command line:

> jsdoc ../sources/webstorm/server/modules -r -d ./api

The difference is the source files will not be included in the documentation. So the output with config file will be ex:

myclass.html

whereas with the command line I will get:

myclass.html
myclass.js.html

I can't seem to understand why the difference in behavior. Is this a bug?

Thanks,
Mathieu.

**Comment by larryaubstore** [comment]
It does not seem to work with this mix: JsDoc3 (3.4.2) + gulp + jsdocConfig.json. 

The documentation is generated but no source code is outputed.

{
  "tags": {
    "allowUnknownTags": true
  },
  "opts": {
    "destination": "./docs/gen"
  },
  "plugins": [
    "plugins/markdown"
  ],
  "templates": {
    "cleverLinks": false,
    "monospaceLinks": false,
    "default": {
      "outputSourceFiles": "true"
    },
    "path": "ink-docstrap",
    "theme": "cerulean",
    "navType": "vertical",
    "linenums": true,
    "dateFormat": "MMMM Do YYYY, h:mm:ss a"
  }
}


var jsdoc       = require('gulp-jsdoc3');
var jsDocConfig = require('./jsdocConfig.json');

********

gulp.task('doc', function (cb) {
    gulp.src(['README.md', 'dist/**/*.js'], {read: true})
        .pipe(jsdoc(jsDocConfig, cb));
});
