### ISSUE TITLE
Parameters of function parameter are labelled as properties

### ISSUE THREAD

**Issue by MacDschie** [jsdoc/jsdoc#462]
Hi there,

I just tried to document the parameters of a callback function which is passed to one of my functions like this:

```
/*
 * ...
 * @param [p_Callback] {Function}
 * Callback for returning the result(s).
 * 
 * <description of callback>
 *   @param p_Callback.p_Err {Error} If an error occurred, the following
 *   parameters will be undefined. Otherwise, `p_Err` is **null**.
 *   ...
```

That produces a nice output - except for the label **Properties** of the callback **Parameters**. I know that this syntax is made for documenting objects, so if there's a better way to do it for callbacks, please let me know. But I like this style, so I suggest to improve JSDoc to write the correct label here.

**Comment by tobiu** [comment]
How would this work for passing a function as a parameter to another function, which is not a callback?

Example:

`    /**
     * Returns all items in the collection for which the passed function returns true
     * @param {function} fn The function to run for each item inside the start-end range. Return true for a match.
     * @param {Object} fn.item The current collection item
     * @param {Object} [scope=this] The scope in which the passed function gets executed
     * @param {Number} [start=0] The start index
     * @param {Number} [end=this.getCount()] The end index (up to, last value excluded)
     * @return {Array} Returns an empty Array in case no items are found
     */
    findBy(fn, scope, start, end) {
        let me    = this,
            items = [],
            i     = start || 0,
            len   = end   || me.getCount();

        scope = scope || me;

        for (; i < len; i++) {
            if (fn.call(scope, me.items[i])) {
                items.push(item);
            }
        }

        return items;
    }`

This way, fn.item shows up as a property and not a param. Is there already a way to document it correctly?

Thx, Tobias
