### ISSUE TITLE
Mention {*} as ALL type for parameters

### ISSUE THREAD

**Issue by SebastianZ** [jsdoc/jsdoc#468]
The [@param](http://usejsdoc.org/tags-param.html) page should define a `{*}` type representing any kind of parameter as it's done at the [Closure Compiler page](https://developers.google.com/closure/compiler/docs/js-for-compiler#types).

I first stumbled over this reading a [stackoverflow thread](http://stackoverflow.com/questions/4909259/how-to-jsdoc-a-mixed-type).

Sebastian

**Comment by rayshan** [comment]
Hi @hegemonic, is the page now supposed to show `{*}`? It doesn't seem to be on there.

**Comment by hegemonic** [comment]
Yes, it's there, under "Allows any type."
