### ISSUE TITLE
Allow users to override the default template's layout file

### ISSUE THREAD

**Issue by hegemonic** [jsdoc/jsdoc#480]
In #472, @sporritt suggested that we allow users to override the `layout.tmpl` file in the default template. That makes it easy to control which CSS/JS files are pulled into each page, even if you don't want to fork the template.

Users should be able to specify another `layout.tmpl` file in the JSDoc config file. The key should be named something like `templates.default.layout` or `templates.default.layoutFile`. It should accept a relative path, to be resolved against...which directories exactly?

**Comment by wangzhaohui** [comment]
Hi,
How can I control the CSS/JS files? I found that the CSS/JS files is permanently linked to defaults. It's not useful to add my CSS link to my customized tmpl
