### ISSUE TITLE
Exclude sub-directories of included directories

### ISSUE THREAD

**Issue by msafi** [jsdoc/jsdoc#484]
Say I have a structure like

```
Server/
|- a.js
|- b.js
|- node_modules
|   |- a bunch of modules...
```

I want to `"include": ["server"]` but I want to exclude `node_modules`. Currently, the only way is to use `excludePattern`, which is a pain. Here's my `excludePattern` right now.

```
"excludePattern": "(^|\\/|\\\\)_|server[\\\\|//]node_modules|js[\\\\|//]lib|css[\\\\|//]lib"
```

It would be much more user friendly if it was possible to simply use an array of excluded sub-directories in `exclude`.

**Comment by danielo515** [comment]
This is not working for me on version 3.4.3, how is this supposed to be used?
