### ISSUE TITLE
@inheritDoc and @override tags support.

### ISSUE THREAD

**Issue by gituliar** [jsdoc/jsdoc#53]
Currently JSDoc ignores `@inheritDoc` and `@override` tags, however it would be nice to replace them with superclass's (modified in case of `@overrride` tag) docstrings in HTML documentation.

**Comment by chharvey** [comment]
What is the difference between `@inheritdoc` and `@override`? I tried swapping one out for the other in my code but I do not see a change in output.

In both cases, it simply repeats the documentation of the inherited member. (I cannot modify, say, a `@param` tag.)

**Comment by ackvf** [comment]
Anyone knows how to make this work in VSCode? I suppose they need to implement support for this tag themselves to display it in the IDE, right?
