### ISSUE TITLE
Can't run jsdoc on the included rhino bundle from Windows command line

### ISSUE THREAD

**Issue by JwJason** [jsdoc/jsdoc#533]
1.) Download the latest jsdoc release; unzip to Desktop
2.) Open cmd.exe, "cd Desktop\jsdoc-master"
3.) "jsdoc --help"

Throws the exception: 

> C:\Users\jason\Desktop\jsdoc-master>jsdoc --help
> js: exception from uncaught JavaScript throw: Error: Module "C:/Users/jason/Desk
> top/jsdoc-master/jsdoc.js" not found.

???

> C:\Users\jason\Desktop\jsdoc-master>dir
>  Volume in drive C has no label.
>  Volume Serial Number is 1A68-B584
> 
> Directory of C:\Users\jason\Desktop\jsdoc-master
> 
> 11/20/2013  10:33 AM    <DIR>          .
> 11/20/2013  10:33 AM    <DIR>          ..
> 11/20/2013  10:33 AM                78 .gitignore
> 11/20/2013  10:33 AM             1,440 .jshintrc
> 11/20/2013  10:33 AM                70 .npmignore
> 11/20/2013  10:33 AM                41 .travis.yml
> 11/20/2013  10:33 AM            11,358 Apache_License_2.0.txt
> 11/20/2013  10:33 AM            19,688 changes.md
> 11/20/2013  10:33 AM             7,117 cli.js
> 11/20/2013  10:33 AM               342 conf.json.EXAMPLE
> 11/20/2013  10:33 AM             3,632 CONTRIBUTING.md
> 11/20/2013  10:33 AM    <DIR>          Jake
> 11/20/2013  10:33 AM             2,355 Jakefile.js
> 11/20/2013  10:33 AM             1,723 jsdoc
> 11/20/2013  10:33 AM             1,505 jsdoc.cmd
> **11/20/2013  10:33 AM             3,457 jsdoc.js**
> 11/20/2013  10:33 AM    <DIR>          lib
> 11/20/2013  10:33 AM            14,079 LICENSE.md
> 11/20/2013  10:33 AM    <DIR>          node
> 11/20/2013  10:33 AM    <DIR>          node_modules
> 11/20/2013  10:33 AM             1,126 package.json
> 11/20/2013  10:33 AM    <DIR>          plugins
> 11/20/2013  10:33 AM             3,168 README.md
> 11/20/2013  10:33 AM    <DIR>          rhino
> 11/20/2013  10:33 AM    <DIR>          templates
> 11/20/2013  10:33 AM    <DIR>          test
>               16 File(s)         71,179 bytes
>               10 Dir(s)   6,362,492,928 bytes free

Windows 7 SP1, 64-bit

**Comment by atomicpages** [comment]
Hi all, encountering this issue when attempting to run tests from Windows via `jsdoc -T`:

Here's the exact error:

```
Running tests...
org.mozilla.javascript.EcmaError: ReferenceError: "self" is not defined.
(file:/C:/Users/djthomps/Desktop/closure/sample4/jsdoc/node_modules/bluebird/js/main/captured_trace.js#464)
```

* Windows 7 SP1 Build 7601
* I installed JSDoc via `git clone https://github.com/jsdoc3/jsdoc.git`
* Java Version, `CLASSPATH`, and `JAVA_HOME`:
```
java version "1.7.0_76"
Java(TM) SE Runtime Environment (build 1.7.0_76-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.76-b04, mixed mode)

set CLASSPATH
Environment variable CLASSPATH not defined

set JAVA_HOME
JAVA_HOME=C:\Program Files\Java\jdk1.7.0_76
```

* JSDoc is installed at: `C:\Users\djthomps\Desktop\closure\sample4\jsdoc`
* After adding the code referenced in https://github.com/jsdoc3/jsdoc/issues/533#issuecomment-29086819
     * I get `file:/C:/Users/djthomps/Desktop/closure/sample4/jsdoc/rhino/js.jar`
* After running `java org.mozilla.javascript.tools.shell.Main`
     * `Error: Could not find or load main class org.mozilla.javascript.tools.shell.Main`

Please let me know if there's any additional information you need!
