### ISSUE TITLE
Large file tree fails on Windows

### ISSUE THREAD

**Issue by terryweiss** [jsdoc/jsdoc#545]
3.3.0-alpha, Windows 

On a project with > 20 folders and about 130 js files, if I run from the root with -r to recurse the tree, jsdoc fails silently, drops back to the command line and the out folder is empty. 

OTOH, if I build the file path, say using grunt, and pass that in, it will work, but only if we aren't too nested already; that is to say near the root of the volume. Each group has a "base.js" module, so the file names end up being "base_", "base__", "base___", etc and so if the path is nested these get pretty long and windows complains, which I am not sure is your problem, but there it is :)

Other than that and one other issue I will add, it is pretty awesomely fast and the docs are essentially what I had under rhino.

**Comment by junedansari** [comment]
Hi,
I am also getting same issue.
I have huge number of files and file name are also somehow long.Getting same issue on window.

Please help me here to sort out same problem
