### ISSUE TITLE
If a symbol's name is all whitespace (or special characters), it gets the wrong name

### ISSUE THREAD

**Issue by mxlle** [jsdoc/jsdoc#549]
I run jsdoc on a directory with its subdirectories. 
There is one file, which hasn't any jsdoc annotations yet. 
But it throws a TagValueRequiredError in this part of the code: 

<pre><code>
var map = {
              '/': '[\\/]',
              '-': '[-]',
              '.': '[.]',
              ' ': '[\\s]',   // THIS LINE THROWS THE ERROR
              'DD': '(?:(?:[0-2]?[0-9]{1})|(?:[3][01]{1}))',
              'D': '(?:(?:[0-2]?[0-9]{1})|(?:[3][01]{1}))',
              'MM': '(?:[0]?[1-9]|[1][012])',
              'M': '(?:[0]?[1-9]|[1][012])',
              'YYYY': '(?:(?:[1]{1}[0-9]{1}[0-9]{1}[0-9]{1})|(?:[2]{1}[0-9]{3}))(?![[0-9]])',
              'YY': '(?:(?:[0-9]{1}[0-9]{1}))(?![[0-9]])'
            };
</code></pre>

I get the following error: 

<pre><code>
TagValueRequiredError: The @name tag requires a value. File: date-range-picker.js, line: 209
</code></pre>

When I remove the affected line, there is no error.

**Comment by telekosmos** [comment]
Mmmmm, this is still happening, at least to me...
I'm using windows 10, and I tried both the (infamous) windows 10 and its Linux subsystem (Ubuntu). I will report the environment for the latter:
```sh
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
$ jsdoc -v
JSDoc 3.4.3 (Thu, 10 Nov 2016 00:25:10 GMT)
$ npm -v
3.10.10
$ node -v
v6.10.0
```
The input file is just like
```js
setGlobalNameSpace("app.core");

/*
 * Configuration Manager object manages every configuration behaviour.
 */
/** @class */
app.core.JsdocTest = Class.extend({
	/** @lends app.core.Configuration.prototype */

	/**
	 * Initialize the Configuration object
	 * @constructs
	 * @param loadConfigurationEvent custom on loading event
	 */
	_initialize : function(loadConfigurationEvent) {
		this.util = env.util;
		this.constants = env.constants;
		this.eventHandler = env.eventHandler;
	},

	/**
	 * Kind of ping method
	 * @param {string} msg optional message
	 * @returns {string} some string replying to the method invocation
	 */
	test: function(msg) {
		return msg? '[JsdocTest.test] Test: '+msg: '[JsdocTest.test] Test';
	}
});
```
Then:
```sh
$ jsdoc DOCS/jsdoctest.js -d ./jsdocdoc/
ERROR: The @name tag requires a value. File: jsdoctest.js, line: 17
```
(line 17 is the _initialize method)
Any chance to get rid of it or we just must ignore it?

Thanks!!!
