### ISSUE TITLE
Some variable assignments trigger "ERROR: The @scope tag is not a known tag" errors

### ISSUE THREAD

**Issue by RoystonS** [jsdoc/jsdoc#574]
If I run jsdoc 3.3.0-alpha4 against the following source file:

``` javascript
define([], function() {
    "use strict";

    /** @exports mymodule */
    var mymodule = {
        /** Some interesting function. */
        someFunction: function() {
            var someValue;
            someValue = 42;
        }
    };

    return mymodule;
});
```

I get an error that reads:
`ERROR: The @scope tag is not a known tag. File: mymodule.js, line: 9`
(It's complaining about the line that reads `someValue = 42;`.)

I'm not using any `@scope` tags: JSDoc seems to be trying to apply an 'inner' scope to my `someValue` var, and trips over itself.

No, this isn't a terribly realistic piece of code: I've just boiled it down to this minimal test case from a much more significant piece of code.  In the original, I'm just assigning to a var in the middle of a function, and it triggers this error.

Thanks!

**Comment by rayshan** [comment]
I just ran into this issue today using `3.3.0-beta1`, does not seem to be fixed. Also not using any `@scope` tags.

```sh
js: "/usr/local/lib/node_modules/jsdoc/jsdoc.js", line 316: exception from uncaught JavaScript throw: UnknownTagError: The @scope tag is not a known tag. File: composer.js, line: 5
```

**Comment by rayshan** [comment]
nevermind my fault, global jsdoc install wasn't latest, sorry for the pings
