### ISSUE TITLE
Help: Full path to source file is displayed in docs and I can't change it.

### ISSUE THREAD

**Issue by janpaepke** [jsdoc/jsdoc#590]
Hi all,

I've been fiddling with this for the last 3 hours and I give up :(

When using the most basic call from MacOsX Terminal to run jsdoc I ALWAYS get the full path of my source file within the generated documentation.
Example:

```
./jsdoc ../project/js/jsfile.js
```

In the generated index file I can see a h1 with "index" and below it a h2 with the full path to the js file:

```
/Users/username/projects/path/projectname/js/jsfile.js
```

After reading up I thought it would be relative to where I run jsdoc from.
But all this has the same exact result:

```
cd /Users/username/projects/path/projectname
../jsdocs-master/jsdoc js/jsfile.js
```

as well as

```
cd /Users/username/projects/path/projectname/js
../../jsdocs-master/jsdoc jsfile.js
```

The problem is, that this path is also used with the line number references. And it's really not nice that my internal path is displayed...

The output I would want is `projectname/js/jsfile.js` or at least just `jsfile.js`, but I can not for the life of me get this to work.

I hope someone can tell me what I'm doing wrong.

regards,
Jan

**Comment by shernshiou** [comment]
hi I am using the latest from git+https://github.com/jsdoc3/jsdoc.git"

As you can see at http://depoio.github.io/node-telegram-bot/Bot.html , it stills display full path.

**Comment by dickeylth** [comment]
Same issue encounted on 3.3.2, it stills display full path. And with more than one source js file it will do right.

**Comment by hegemonic** [comment]
@shernshiou @dickeylth This may be an issue with the template you're using. If you can reproduce this issue with JSDoc's default template, please file a new bug. Otherwise, file a bug against the template you're using.
