### ISSUE TITLE
Prototype methods not showing up without memberof

### ISSUE THREAD

**Issue by zcourts** [jsdoc/jsdoc#596]
This may be a regression on https://github.com/jsdoc3/jsdoc/issues/30 but if I document an AMD function and add functions to it's prototype I have to manually add the memberof tag to get the methods to show up.

e.g.

``` javascript

define('MyFunc',
    [
        'SomeModule'
    ], function (SomeModule) {
        /**
         * Some module desc
         * @mixin
         * @global
         */
        function MyFunc() {
        }

        /**
         * Sets the given name value pair on the object
         * @param k the name/key
         * @param v the value to assign to the name/key
         * @memberof MyFunc
         */
        MyFunc.prototype.set = function ( k, v) {
            this.attr[k] = v;
        };

        /**
         * Gets a previously set attribute
         * @param k the name/key of the attribute to get
         * @memberof MyFunc
         * @returns {*} the value previously set or undefined if it doesn't exist
         */
        MyFunc.prototype.get = function (k) {
            return this.attr[k];
        };

        return SomeModule([], MyFunc);
    });


```

I'd expect get and set to be automatically documented as methods of MyFunc without me telling it with memberof. 
I also have to mark MyFunc as global for it to be documented, maybe additional support for AMD modules is needed?
Might also be relevant to mention that I can't seem to get anything put under a namespace. If the namespace tag is added to a function and I use memberof namespaceName the namespace's page is still just blank

``` shell
jsdoc --version
JSDoc 3.3.0-alpha4 (Sun, 26 Jan 2014 04:51:18 GMT)
```

**Comment by j-ulrich** [comment]
See also [my comment](https://github.com/jsdoc3/jsdoc/issues/495#issuecomment-129924254) on #495 to avoid the duplication of the `@memberof` tags.

**Comment by mrself** [comment]
It is really weird that inside `define` callback jsdoc does not recognize syntax. When I just define a simple function and put there the same code (with `MyFunc`), it is recognized.
