### ISSUE TITLE
NPM Install jsdoc@"<=3.3.0" failing on Windows 7

### ISSUE THREAD

**Issue by aksagni** [jsdoc/jsdoc#598]
Following are the configurations used:
NPM - 1.3.14, Node - 0.10.22, grunt - 0.4.2, grunt-cli - 0.1.13
git version 1.9.0.msysgit.0

Proxy used as per the format below.
npm config set proxy http://proxy.company.com:8080
npm config set https-proxy http://proxy.company.com:8080
git config --global http.proxy http://proxy.company.com:8080

---

Logs:
npm http GET https://registry.npmjs.org/jsdoc
npm http 200 https://registry.npmjs.org/jsdoc
npm http GET https://registry.npmjs.org/jsdoc/-/jsdoc-3.3.0-alpha4.tgz
npm http 200 https://registry.npmjs.org/jsdoc/-/jsdoc-3.3.0-alpha4.tgz
npm http GET https://registry.npmjs.org/catharsis
npm http GET https://registry.npmjs.org/esprima
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/js2xmlparser
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/marked
npm http GET https://registry.npmjs.org/wrench
npm http 200 https://registry.npmjs.org/js2xmlparser
npm http GET https://registry.npmjs.org/js2xmlparser/-/js2xmlparser-0.1.3.tgz
npm http 200 https://registry.npmjs.org/esprima
npm http GET https://registry.npmjs.org/esprima/-/esprima-1.0.4.tgz
npm http 200 https://registry.npmjs.org/marked
npm http 200 https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/marked/-/marked-0.2.10.tgz
npm http GET https://registry.npmjs.org/underscore/-/underscore-1.4.4.tgz
npm http 200 https://registry.npmjs.org/wrench
npm http GET https://registry.npmjs.org/wrench/-/wrench-1.3.9.tgz
npm http 200 https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/async/-/async-0.1.22.tgz
npm http 200 https://registry.npmjs.org/catharsis
npm http GET https://registry.npmjs.org/catharsis/-/catharsis-0.7.0.tgz
npm http 200 https://registry.npmjs.org/esprima/-/esprima-1.0.4.tgz
npm http 200 https://registry.npmjs.org/js2xmlparser/-/js2xmlparser-0.1.3.tgz
npm http 200 https://registry.npmjs.org/underscore/-/underscore-1.4.4.tgz
npm http 200 https://registry.npmjs.org/marked/-/marked-0.2.10.tgz
npm http 200 https://registry.npmjs.org/wrench/-/wrench-1.3.9.tgz
npm http 200 https://registry.npmjs.org/async/-/async-0.1.22.tgz
npm http 200 https://registry.npmjs.org/catharsis/-/catharsis-0.7.0.tgz
npm ERR! git clone https://github.com/hegemonic/taffydb.git Cloning into bare re
pository 'C:\Users\a487010\AppData\Roaming\npm-cache_git-remotes\https-github-c
om-hegemonic-taffydb-git-386cf83c'...
npm ERR! git clone https://github.com/hegemonic/taffydb.git fatal: unable to acc
ess 'https://github.com/hegemonic/taffydb.git/': Could not resolve host: github.
com
npm ERR! Error: Command failed: Cloning into bare repository 'C:\Users\a487010\A
ppData\Roaming\npm-cache_git-remotes\https-github-com-hegemonic-taffydb-git-386
cf83c'...
npm ERR! fatal: unable to access 'https://github.com/hegemonic/taffydb.git/': Co
uld not resolve host: github.com
npm ERR!
npm ERR!     at ChildProcess.exithandler (child_process.js:637:15)
npm ERR!     at ChildProcess.EventEmitter.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:735:16)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:802:5)
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\Program_Files\nodejs\\node.exe" "C:\Program_Files\nod
ejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "jsdoc@<=3.3.0"
npm ERR! cwd C:\xampp\htdocs\Examples\ses-svn
npm ERR! node -v v0.10.22
npm ERR! npm -v 1.3.14
npm ERR! code 128
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\xampp\htdocs\Examples\ses-svn\npm-debug.log
npm ERR! not ok code 0

**Comment by spawnrider** [comment]
Hi,

Could you please use the NPM Registry reference instead of the Github package ? 
https://www.npmjs.com/package/taffydb
