### ISSUE TITLE
Error: unable to parse... but "<" found

### ISSUE THREAD

**Issue by JamesMGreene** [jsdoc/jsdoc#654]
I'm trying to use jsdoc but hitting failures.

I tried this with:
- `grunt-jsdoc@0.5.4` (currently using `jsdoc@3.2.2`)
- `jsdoc@3.3.0-alpha5`
- `jsdoc@3.3.0-dev` (latest `master`)

I received the same error from all of these versions.

``` shell
$ ./node_modules/jsdoc/jsdoc dist/ZeroClipboard.js

[Error: unable to parse <anonymous>~ZeroClipboard._createClient: Expected "!", "$", "(", "*", "...", "?", "Function", "\\", "_", "break", "case", "catch", "class", "const", "continue", "debugger", "default", "delete", "do", "else", "enum", "export", "extends", "false", "finally", "for", "function", "if", "implements", "import", "in", "instanceof", "interface", "let", "new", "null", "package", "private", "protected", "public", "return", "static", "super", "switch", "this", "throw", "true", "try", "typeof", "undefined", "var", "void", "while", "with", "yield", "{", Unicode letter number, Unicode lowercase letter, Unicode modifier letter, Unicode other letter, Unicode titlecase letter or Unicode uppercase letter but "<" found.]
```

Here's a snapshot of the file in question: [`dist/ZeroClipboard.js`@`a4ef8ad`](https://github.com/zeroclipboard/zeroclipboard/blob/a4ef8ad3d27946c71aff7e5cbc69290c3751cf41/dist/ZeroClipboard.js).

I don't see any problems with the source, so I'm assuming something is getting messed up in the [presumably created] AST.

**Comment by ccoenen** [comment]
I still have this bug with 3.3.0-beta1

    C:\Users\user\workspace\project> node_modules\.bin\jsdoc --version
    JSDoc 3.3.0-beta1 (Wed, 21 Jan 2015 17:41:43 GMT)
    
    C:\Users\user\workspace\project>"node_modules/.bin/jsdoc" -d "./doc/jsdoc" -p ./src/Drive.Core.js ./src/Drive.Loading.js ./src/Drive.Debug.js ./src/Drive.URL.js ./src/Drive.Locale.js ./src/Drive.Navigation.js ./src/Drive.Transition.js ./src/Drive.Component.js ./src/Drive.Scene.js
    [Error: unable to parse <a href="Drive.html#useComponent()">#useComponent()</a>: Expected "!", "$", "'", "(", "*", "...", "?", "Function", "\"", "\\", "_", "break", "case", "catch", "class", "const", "continue", "debugger", "default", "delete", "do", "else", "enum", "export", "extends", "false", "finally", "for", "function", "if", "implements", "import", "in", "instanceof", "interface", "let", "new", "null", "package", "private", "protected", "public", "return", "static", "super", "switch", "this", "throw", "true", "try", "typeof", "undefined", "var", "void", "while", "with", "yield", "{", Unicode letter number, Unicode lowercase letter, Unicode modifier letter, Unicode other letter, Unicode titlecase letter or Unicode uppercase letter but "<" found.]

Is there any way i can help debug it?

**Comment by hegemonic** [comment]
@ccoenen That looks like a different bug. Please file a new issue, including sample code that triggers the issue.
