### ISSUE TITLE
How to document chainable return values?

### ISSUE THREAD

**Issue by pocesar** [jsdoc/jsdoc#669]
I have multiple classes that I want to show that the method return the instance of the current instantiated class, how is it possible?

``` js
/**
 * @class MyClass
 */
MyClass = (function(_super){
  __extends(MyClass, _super);
  /**
   * @memberof MyClass
   * @instance
   * @return {MyClass} what should go here?
   */
  MyClass.prototype.myFunc = function(){
     return this;
  };
  /* ... rest of code ... */
})(BaseClass);
```

**Comment by trusktr** [comment]
@hegemonic I think this is a feature request got `@chainable`, which informs that the method is chainable.

**Comment by trusktr** [comment]
@pocesar Here's one way you could do it. Look at this library (search results for "chainable" to see how methods are denoted as chainable: https://github.com/lazd/F/search?utf8=%E2%9C%93&q=chainable

And then, check out some sample docs generated from those jsdoc comments (search for "chainable"): http://blog.lazd.net/F/F/jsdoc/F.View.html

**Comment by Reinmar** [comment]
:+1: for `@chainable`. More verbose than just `@returns {MyClass} this`.

**Comment by dcollinsf5** [comment]
+1 - Would also like @chainable

**Comment by fsmaia** [comment]
+1 for `@chainable`

**Comment by WRidder** [comment]
+1 for @chainable

**Comment by rahbari** [comment]
+1 for @chainable, it's more readable!

**Comment by christiantjl** [comment]
+1 for `@chainable`, but it's clearly not happening.
