### ISSUE TITLE
Generate markdown documentation from docblocks

### ISSUE THREAD

**Issue by mrjoelkemp** [jsdoc/jsdoc#709]
Hey @hegemonic, would you be open to bringing markdown documentation generation to the jsdoc repo? I'm _not_ referring to parsing markdown within a docblock, I'm talking about having markdown instead of html as output from the jsdoc binary. 

I'm thinking of output similar to what [jsdox](https://github.com/sutoiku/jsdox/blob/master/sample_output/test.md) produces.

**Comment by 75lb** [comment]
hey @mrjoelkemp, @hegemonic - long time no speak! 

i'm still working on the next version, it's not ready for release, but your input would help at this point! Quick examples of new output: 
https://github.com/75lb/famous-map/blob/master/docs.md
https://github.com/75lb/handbrake-js

install it
`$ npm install -g jsdoc-to-markdown@next`

then try it for yourself: 
`$ jsdoc2md *.js > docs.md`

take a look at the new options:
`$ jsdoc2md --help`

let me know of any flaws etc.. meanwhile i need to iron a few more things out then update the docs..

**Comment by 75lb** [comment]
it also works on `.html` files if you pass `--html`.. it uses the [`parseHtml` plugin](https://github.com/jsdoc3/jsdoc/pull/723)..

**Comment by hegemonic** [comment]
@75lb Nice work! I probably won't get a chance to look at this closely, but if I do, I'll be sure to send feedback. And once you've released this, be sure to send a pull request to add this to the list of tools in the README.
