### ISSUE TITLE
Property tag allows [optional=default] but not =default format

### ISSUE THREAD

**Issue by mscuthbert** [jsdoc/jsdoc#791]
I'm pretty new to jsdoc3 so I may have missed something, but I love using the 

```
@property {string} name - person's name
```

format, especially since I'm in an AMD environment where I seem to need `@memberof` otherwise to document a value.  I've noticed though that

```
@property {string} name="Mary" - person's name
```

does not work for showing the default value of the property (in cases where there is a static default), but documenting it as an optional `@param` attribute does work:

```
@property {string} [name="Mary"] - person's name
```

This, however, puts a designation in the generated documentation that it is optional (all properties are...). Is there a workaround or is this a bug in the system? (if support for the last one IS a bug, please don't remove it!) Thanks!

**Comment by iniatse** [comment]
Anybody?

**Comment by NielsPichon** [comment]
@iniatse Have you found a solution? I have found that ] and spaces always get registered as part of the description, not the default value.
